package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20170404
  */
case class AgreementIDField(override val value: String) extends SfFieldString(914, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(914)AgreementID=(").append(value).append(")")
}

object AgreementIDField {
  val TagId = 914  
  def decode(a: Option[Any]) : Option[AgreementIDField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[AgreementIDField]
  }

  def decode(a: Any) : Option[AgreementIDField] = a match {
    case v: String => Some(AgreementIDField(v))
    case v: AgreementIDField => Some(v)
    case _ => scala.Option.empty[AgreementIDField]
  } 
}
