package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldFloat

/**
  * Generated by SackFix code generator on 20210314
  */
case class AllowableOneSidednessPctField(override val value: Float) extends SfFieldFloat(765, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(765)AllowableOneSidednessPct=(").append(value).append(")")
}

object AllowableOneSidednessPctField {
  val TagId = 765  
  def apply(value: String) = try {
    new AllowableOneSidednessPctField(value.toFloat)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new AllowableOneSidednessPct("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[AllowableOneSidednessPctField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[AllowableOneSidednessPctField]
  }

  def decode(a: Any) : Option[AllowableOneSidednessPctField] = a match {
    case v: String => Some(AllowableOneSidednessPctField(v))
    case v: Float => Some(AllowableOneSidednessPctField(v))
    case v: Double => Some(AllowableOneSidednessPctField(v.toFloat))
    case v: Int => Some(AllowableOneSidednessPctField(v.toFloat))
    case v: AllowableOneSidednessPctField => Some(v)
    case _ => scala.Option.empty[AllowableOneSidednessPctField]
  } 
}
