package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldBoolean

/**
  * Generated by SackFix code generator on 20210314
  */
case class ApplResendFlagField(override val value: Boolean) extends SfFieldBoolean(1352, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(1352)ApplResendFlag=(").append({if (value) "Y" else "N"}).append(")")
}

object ApplResendFlagField {
  val TagId = 1352  
  def apply(value: String) = try {
    new ApplResendFlagField(value match {
      case "Y" => true
      case "N" => false
      case _ => throw new IllegalArgumentException("ApplResendFlag.apply("+value+"] failed, bad value, expected Y or N.")
    })
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new ApplResendFlag("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[ApplResendFlagField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[ApplResendFlagField]
  }

  def decode(a: Any) : Option[ApplResendFlagField] = a match {
    case v: String => Some(ApplResendFlagField(v))
    case v: Boolean => Some(ApplResendFlagField(v))
    case v: ApplResendFlagField => Some(v)
    case _ => scala.Option.empty[ApplResendFlagField]
  } 
}
