package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldInt

/**
  * Generated by SackFix code generator on 20210314
  */
case class ApplEndSeqNumField(override val value: Int) extends SfFieldInt(1183, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(1183)ApplEndSeqNum=(").append(value).append(")")
}

object ApplEndSeqNumField {
  val TagId = 1183  
  def apply(value: String) = try {
    new ApplEndSeqNumField(value.toInt)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new ApplEndSeqNum("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[ApplEndSeqNumField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[ApplEndSeqNumField]
  }

  def decode(a: Any) : Option[ApplEndSeqNumField] = a match {
    case v: String => Some(ApplEndSeqNumField(v))
    case v: Int => Some(ApplEndSeqNumField(v))
    case v: ApplEndSeqNumField => Some(v)
    case _ => scala.Option.empty[ApplEndSeqNumField]
  } 
}
