package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldInt

/**
  * Generated by SackFix code generator on 20210314
  */
case class ApplQueueActionField(override val value: Int) extends SfFieldInt(815, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(815)ApplQueueAction=(").append(value).append(")").append(ApplQueueActionField.fixDescriptionByValue.getOrElse(value,""))
}

object ApplQueueActionField {
  val TagId = 815 
  val NoActionTaken=0
  val QueueFlushed=1
  val OverlayLast=2
  val EndSession=3
  lazy val fixDescriptionByValue = Map(0->"NO_ACTION_TAKEN",1->"QUEUE_FLUSHED",
    2->"OVERLAY_LAST",3->"END_SESSION")
 
  def apply(value: String) = try {
    new ApplQueueActionField(value.toInt)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new ApplQueueAction("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[ApplQueueActionField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[ApplQueueActionField]
  }

  def decode(a: Any) : Option[ApplQueueActionField] = a match {
    case v: String => Some(ApplQueueActionField(v))
    case v: Int => Some(ApplQueueActionField(v))
    case v: ApplQueueActionField => Some(v)
    case _ => scala.Option.empty[ApplQueueActionField]
  } 
}
