package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldInt

/**
  * Generated by SackFix code generator on 20170404
  */
case class AvgPxPrecisionField(override val value: Int) extends SfFieldInt(74, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(74)AvgPxPrecision=(").append(value).append(")")
}

object AvgPxPrecisionField {
  val TagId = 74  
  def apply(value: String) = try {
    new AvgPxPrecisionField(value.toInt)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new AvgPxPrecision("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[AvgPxPrecisionField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[AvgPxPrecisionField]
  }

  def decode(a: Any) : Option[AvgPxPrecisionField] = a match {
    case v: String => Some(AvgPxPrecisionField(v))
    case v: Int => Some(AvgPxPrecisionField(v))
    case v: AvgPxPrecisionField => Some(v)
    case _ => scala.Option.empty[AvgPxPrecisionField]
  } 
}
