package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20170521
  */
case class CardNumberField(override val value: String) extends SfFieldString(489, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(489)CardNumber=(").append(value).append(")")
}

object CardNumberField {
  val TagId = 489  
  def decode(a: Option[Any]) : Option[CardNumberField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[CardNumberField]
  }

  def decode(a: Any) : Option[CardNumberField] = a match {
    case v: String => Some(CardNumberField(v))
    case v: CardNumberField => Some(v)
    case _ => scala.Option.empty[CardNumberField]
  } 
}
