package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldLocalMktDate
import java.time.LocalDate
import org.sackfix.common.validated.fields.SfFixDateFormats

/**
  * Generated by SackFix code generator on 20210314
  */
case class CardExpDateField(override val value: LocalDate) extends SfFieldLocalMktDate(490, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(490)CardExpDate=(").append(value).append(")")
}

object CardExpDateField {
  val TagId = 490  
  def apply(value: String) = try {
    new CardExpDateField(LocalDate.from(SfFixDateFormats.localMktDate.parse(value)))
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new CardExpDate("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[CardExpDateField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[CardExpDateField]
  }

  def decode(a: Any) : Option[CardExpDateField] = a match {
    case v: String => Some(CardExpDateField(v))
    case v: LocalDate => Some(CardExpDateField(v))
    case v: CardExpDateField => Some(v)
    case _ => scala.Option.empty[CardExpDateField]
  } 
}
