package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldFloat

/**
  * Generated by SackFix code generator on 20170404
  */
case class CashOrderQtyField(override val value: Float) extends SfFieldFloat(152, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(152)CashOrderQty=(").append(value).append(")")
}

object CashOrderQtyField {
  val TagId = 152  
  def apply(value: String) = try {
    new CashOrderQtyField(value.toFloat)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new CashOrderQty("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[CashOrderQtyField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[CashOrderQtyField]
  }

  def decode(a: Any) : Option[CashOrderQtyField] = a match {
    case v: String => Some(CashOrderQtyField(v))
    case v: Float => Some(CashOrderQtyField(v))
    case v: Double => Some(CashOrderQtyField(v.toFloat))
    case v: Int => Some(CashOrderQtyField(v.toFloat))
    case v: CashOrderQtyField => Some(v)
    case _ => scala.Option.empty[CashOrderQtyField]
  } 
}
