package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldUtcTimeStamp
import java.time.LocalDateTime
import org.sackfix.common.validated.fields.SfFixDateFormats

/**
  * Generated by SackFix code generator on 20170521
  */
case class ComplexEventEndDateField(override val value: LocalDateTime) extends SfFieldUtcTimeStamp(1493, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(1493)ComplexEventEndDate=(").append(value).append(")")
}

object ComplexEventEndDateField {
  val TagId = 1493  
  def apply(value: String) = try {
    new ComplexEventEndDateField(LocalDateTime.from(SfFixDateFormats.utcTimeStamp.parse(value)))
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new ComplexEventEndDate("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[ComplexEventEndDateField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[ComplexEventEndDateField]
  }

  def decode(a: Any) : Option[ComplexEventEndDateField] = a match {
    case v: String => Some(ComplexEventEndDateField(v))
    case v: LocalDateTime => Some(ComplexEventEndDateField(v))
    case v: ComplexEventEndDateField => Some(v)
    case _ => scala.Option.empty[ComplexEventEndDateField]
  } 
}
