package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldFloat

/**
  * Generated by SackFix code generator on 20170521
  */
case class CouponRateField(override val value: Float) extends SfFieldFloat(223, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(223)CouponRate=(").append(value).append(")")
}

object CouponRateField {
  val TagId = 223  
  def apply(value: String) = try {
    new CouponRateField(value.toFloat)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new CouponRate("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[CouponRateField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[CouponRateField]
  }

  def decode(a: Any) : Option[CouponRateField] = a match {
    case v: String => Some(CouponRateField(v))
    case v: Float => Some(CouponRateField(v))
    case v: Double => Some(CouponRateField(v.toFloat))
    case v: Int => Some(CouponRateField(v.toFloat))
    case v: CouponRateField => Some(v)
    case _ => scala.Option.empty[CouponRateField]
  } 
}
