package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldFloat

/**
  * Generated by SackFix code generator on 20170521
  */
case class CumQtyField(override val value: Float) extends SfFieldFloat(14, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(14)CumQty=(").append(value).append(")")
}

object CumQtyField {
  val TagId = 14  
  def apply(value: String) = try {
    new CumQtyField(value.toFloat)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new CumQty("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[CumQtyField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[CumQtyField]
  }

  def decode(a: Any) : Option[CumQtyField] = a match {
    case v: String => Some(CumQtyField(v))
    case v: Float => Some(CumQtyField(v))
    case v: Double => Some(CumQtyField(v.toFloat))
    case v: Int => Some(CumQtyField(v.toFloat))
    case v: CumQtyField => Some(v)
    case _ => scala.Option.empty[CumQtyField]
  } 
}
