package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldFloat

/**
  * Generated by SackFix code generator on 20170404
  */
case class DayOrderQtyField(override val value: Float) extends SfFieldFloat(424, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(424)DayOrderQty=(").append(value).append(")")
}

object DayOrderQtyField {
  val TagId = 424  
  def apply(value: String) = try {
    new DayOrderQtyField(value.toFloat)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new DayOrderQty("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[DayOrderQtyField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[DayOrderQtyField]
  }

  def decode(a: Any) : Option[DayOrderQtyField] = a match {
    case v: String => Some(DayOrderQtyField(v))
    case v: Float => Some(DayOrderQtyField(v))
    case v: Double => Some(DayOrderQtyField(v.toFloat))
    case v: Int => Some(DayOrderQtyField(v.toFloat))
    case v: DayOrderQtyField => Some(v)
    case _ => scala.Option.empty[DayOrderQtyField]
  } 
}
