package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20170521
  */
case class DeliverToSubIDField(override val value: String) extends SfFieldString(129, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(129)DeliverToSubID=(").append(value).append(")")
}

object DeliverToSubIDField {
  val TagId = 129  
  def decode(a: Option[Any]) : Option[DeliverToSubIDField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[DeliverToSubIDField]
  }

  def decode(a: Any) : Option[DeliverToSubIDField] = a match {
    case v: String => Some(DeliverToSubIDField(v))
    case v: DeliverToSubIDField => Some(v)
    case _ => scala.Option.empty[DeliverToSubIDField]
  } 
}
