package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldInt

/**
  * Generated by SackFix code generator on 20170404
  */
case class DerivativeEventTypeField(override val value: Int) extends SfFieldInt(1287, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(1287)DerivativeEventType=(").append(value).append(")")
}

object DerivativeEventTypeField {
  val TagId = 1287  
  def apply(value: String) = try {
    new DerivativeEventTypeField(value.toInt)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new DerivativeEventType("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[DerivativeEventTypeField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[DerivativeEventTypeField]
  }

  def decode(a: Any) : Option[DerivativeEventTypeField] = a match {
    case v: String => Some(DerivativeEventTypeField(v))
    case v: Int => Some(DerivativeEventTypeField(v))
    case v: DerivativeEventTypeField => Some(v)
    case _ => scala.Option.empty[DerivativeEventTypeField]
  } 
}
