package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20170521
  */
case class DerivativeFuturesValuationMethodField(override val value: String) extends SfFieldString(1319, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(1319)DerivativeFuturesValuationMethod=(").append(value).append(")")
}

object DerivativeFuturesValuationMethodField {
  val TagId = 1319  
  def decode(a: Option[Any]) : Option[DerivativeFuturesValuationMethodField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[DerivativeFuturesValuationMethodField]
  }

  def decode(a: Any) : Option[DerivativeFuturesValuationMethodField] = a match {
    case v: String => Some(DerivativeFuturesValuationMethodField(v))
    case v: DerivativeFuturesValuationMethodField => Some(v)
    case _ => scala.Option.empty[DerivativeFuturesValuationMethodField]
  } 
}
