package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20210314
  */
case class DerivativeSecurityAltIDField(override val value: String) extends SfFieldString(1219, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(1219)DerivativeSecurityAltID=(").append(value).append(")")
}

object DerivativeSecurityAltIDField {
  val TagId = 1219  
  def decode(a: Option[Any]) : Option[DerivativeSecurityAltIDField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[DerivativeSecurityAltIDField]
  }

  def decode(a: Any) : Option[DerivativeSecurityAltIDField] = a match {
    case v: String => Some(DerivativeSecurityAltIDField(v))
    case v: DerivativeSecurityAltIDField => Some(v)
    case _ => scala.Option.empty[DerivativeSecurityAltIDField]
  } 
}
