package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldInt

/**
  * Generated by SackFix code generator on 20170521
  */
case class DerivativeListMethodField(override val value: Int) extends SfFieldInt(1320, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(1320)DerivativeListMethod=(").append(value).append(")")
}

object DerivativeListMethodField {
  val TagId = 1320  
  def apply(value: String) = try {
    new DerivativeListMethodField(value.toInt)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new DerivativeListMethod("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[DerivativeListMethodField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[DerivativeListMethodField]
  }

  def decode(a: Any) : Option[DerivativeListMethodField] = a match {
    case v: String => Some(DerivativeListMethodField(v))
    case v: Int => Some(DerivativeListMethodField(v))
    case v: DerivativeListMethodField => Some(v)
    case _ => scala.Option.empty[DerivativeListMethodField]
  } 
}
