package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldFloat

/**
  * Generated by SackFix code generator on 20170404
  */
case class DerivativeStrikePriceField(override val value: Float) extends SfFieldFloat(1261, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(1261)DerivativeStrikePrice=(").append(value).append(")")
}

object DerivativeStrikePriceField {
  val TagId = 1261  
  def apply(value: String) = try {
    new DerivativeStrikePriceField(value.toFloat)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new DerivativeStrikePrice("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[DerivativeStrikePriceField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[DerivativeStrikePriceField]
  }

  def decode(a: Any) : Option[DerivativeStrikePriceField] = a match {
    case v: String => Some(DerivativeStrikePriceField(v))
    case v: Float => Some(DerivativeStrikePriceField(v))
    case v: Double => Some(DerivativeStrikePriceField(v.toFloat))
    case v: Int => Some(DerivativeStrikePriceField(v.toFloat))
    case v: DerivativeStrikePriceField => Some(v)
    case _ => scala.Option.empty[DerivativeStrikePriceField]
  } 
}
