package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20210314
  */
case class DerivativeSecurityIDSourceField(override val value: String) extends SfFieldString(1217, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(1217)DerivativeSecurityIDSource=(").append(value).append(")")
}

object DerivativeSecurityIDSourceField {
  val TagId = 1217  
  def decode(a: Option[Any]) : Option[DerivativeSecurityIDSourceField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[DerivativeSecurityIDSourceField]
  }

  def decode(a: Any) : Option[DerivativeSecurityIDSourceField] = a match {
    case v: String => Some(DerivativeSecurityIDSourceField(v))
    case v: DerivativeSecurityIDSourceField => Some(v)
    case _ => scala.Option.empty[DerivativeSecurityIDSourceField]
  } 
}
