package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldInt

/**
  * Generated by SackFix code generator on 20170521
  */
case class DerivativeSecurityXMLLenField(override val value: Int) extends SfFieldInt(1282, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(1282)DerivativeSecurityXMLLen=(").append(value).append(")")
}

object DerivativeSecurityXMLLenField {
  val TagId = 1282  
  def apply(value: String) = try {
    new DerivativeSecurityXMLLenField(value.toInt)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new DerivativeSecurityXMLLen("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[DerivativeSecurityXMLLenField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[DerivativeSecurityXMLLenField]
  }

  def decode(a: Any) : Option[DerivativeSecurityXMLLenField] = a match {
    case v: String => Some(DerivativeSecurityXMLLenField(v))
    case v: Int => Some(DerivativeSecurityXMLLenField(v))
    case v: DerivativeSecurityXMLLenField => Some(v)
    case _ => scala.Option.empty[DerivativeSecurityXMLLenField]
  } 
}
