package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20170521
  */
case class DerivativeSecurityXMLDataField(override val value: String) extends SfFieldString(1283, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(1283)DerivativeSecurityXMLData=(").append(value).append(")")
}

object DerivativeSecurityXMLDataField {
  val TagId = 1283  
  def decode(a: Option[Any]) : Option[DerivativeSecurityXMLDataField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[DerivativeSecurityXMLDataField]
  }

  def decode(a: Any) : Option[DerivativeSecurityXMLDataField] = a match {
    case v: String => Some(DerivativeSecurityXMLDataField(v))
    case v: DerivativeSecurityXMLDataField => Some(v)
    case _ => scala.Option.empty[DerivativeSecurityXMLDataField]
  } 
}
