package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldInt

/**
  * Generated by SackFix code generator on 20170404
  */
case class DiscretionMoveTypeField(override val value: Int) extends SfFieldInt(841, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(841)DiscretionMoveType=(").append(value).append(")").append(DiscretionMoveTypeField.fixDescriptionByValue.getOrElse(value,""))
}

object DiscretionMoveTypeField {
  val TagId = 841 
  val Floating=0
  val Fixed=1
  lazy val fixDescriptionByValue = Map(0->"FLOATING",1->"FIXED")
 
  def apply(value: String) = try {
    new DiscretionMoveTypeField(value.toInt)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new DiscretionMoveType("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[DiscretionMoveTypeField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[DiscretionMoveTypeField]
  }

  def decode(a: Any) : Option[DiscretionMoveTypeField] = a match {
    case v: String => Some(DiscretionMoveTypeField(v))
    case v: Int => Some(DiscretionMoveTypeField(v))
    case v: DiscretionMoveTypeField => Some(v)
    case _ => scala.Option.empty[DiscretionMoveTypeField]
  } 
}
