package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldFloat

/**
  * Generated by SackFix code generator on 20210314
  */
case class DiscretionPriceField(override val value: Float) extends SfFieldFloat(845, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(845)DiscretionPrice=(").append(value).append(")")
}

object DiscretionPriceField {
  val TagId = 845  
  def apply(value: String) = try {
    new DiscretionPriceField(value.toFloat)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new DiscretionPrice("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[DiscretionPriceField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[DiscretionPriceField]
  }

  def decode(a: Any) : Option[DiscretionPriceField] = a match {
    case v: String => Some(DiscretionPriceField(v))
    case v: Float => Some(DiscretionPriceField(v))
    case v: Double => Some(DiscretionPriceField(v.toFloat))
    case v: Int => Some(DiscretionPriceField(v.toFloat))
    case v: DiscretionPriceField => Some(v)
    case _ => scala.Option.empty[DiscretionPriceField]
  } 
}
