package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldFloat

/**
  * Generated by SackFix code generator on 20170404
  */
case class DisplayMinIncrField(override val value: Float) extends SfFieldFloat(1087, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(1087)DisplayMinIncr=(").append(value).append(")")
}

object DisplayMinIncrField {
  val TagId = 1087  
  def apply(value: String) = try {
    new DisplayMinIncrField(value.toFloat)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new DisplayMinIncr("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[DisplayMinIncrField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[DisplayMinIncrField]
  }

  def decode(a: Any) : Option[DisplayMinIncrField] = a match {
    case v: String => Some(DisplayMinIncrField(v))
    case v: Float => Some(DisplayMinIncrField(v))
    case v: Double => Some(DisplayMinIncrField(v.toFloat))
    case v: Int => Some(DisplayMinIncrField(v.toFloat))
    case v: DisplayMinIncrField => Some(v)
    case _ => scala.Option.empty[DisplayMinIncrField]
  } 
}
