package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldFloat

/**
  * Generated by SackFix code generator on 20170404
  */
case class DividendYieldField(override val value: Float) extends SfFieldFloat(1380, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(1380)DividendYield=(").append(value).append(")")
}

object DividendYieldField {
  val TagId = 1380  
  def apply(value: String) = try {
    new DividendYieldField(value.toFloat)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new DividendYield("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[DividendYieldField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[DividendYieldField]
  }

  def decode(a: Any) : Option[DividendYieldField] = a match {
    case v: String => Some(DividendYieldField(v))
    case v: Float => Some(DividendYieldField(v))
    case v: Double => Some(DividendYieldField(v.toFloat))
    case v: Int => Some(DividendYieldField(v.toFloat))
    case v: DividendYieldField => Some(v)
    case _ => scala.Option.empty[DividendYieldField]
  } 
}
