package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20170404
  */
case class DlvyInstField(override val value: String) extends SfFieldString(86, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(86)DlvyInst=(").append(value).append(")")
}

object DlvyInstField {
  val TagId = 86  
  def decode(a: Option[Any]) : Option[DlvyInstField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[DlvyInstField]
  }

  def decode(a: Any) : Option[DlvyInstField] = a match {
    case v: String => Some(DlvyInstField(v))
    case v: DlvyInstField => Some(v)
    case _ => scala.Option.empty[DlvyInstField]
  } 
}
