package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldFloat

/**
  * Generated by SackFix code generator on 20170404
  */
case class EFPTrackingErrorField(override val value: Float) extends SfFieldFloat(405, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(405)EFPTrackingError=(").append(value).append(")")
}

object EFPTrackingErrorField {
  val TagId = 405  
  def apply(value: String) = try {
    new EFPTrackingErrorField(value.toFloat)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new EFPTrackingError("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[EFPTrackingErrorField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[EFPTrackingErrorField]
  }

  def decode(a: Any) : Option[EFPTrackingErrorField] = a match {
    case v: String => Some(EFPTrackingErrorField(v))
    case v: Float => Some(EFPTrackingErrorField(v))
    case v: Double => Some(EFPTrackingErrorField(v.toFloat))
    case v: Int => Some(EFPTrackingErrorField(v.toFloat))
    case v: EFPTrackingErrorField => Some(v)
    case _ => scala.Option.empty[EFPTrackingErrorField]
  } 
}
