package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20210314
  */
case class EncodedIssuerField(override val value: String) extends SfFieldString(349, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(349)EncodedIssuer=(").append(value).append(")")
}

object EncodedIssuerField {
  val TagId = 349  
  def decode(a: Option[Any]) : Option[EncodedIssuerField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[EncodedIssuerField]
  }

  def decode(a: Any) : Option[EncodedIssuerField] = a match {
    case v: String => Some(EncodedIssuerField(v))
    case v: EncodedIssuerField => Some(v)
    case _ => scala.Option.empty[EncodedIssuerField]
  } 
}
