package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20170404
  */
case class EncodedSecurityListDescField(override val value: String) extends SfFieldString(1469, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(1469)EncodedSecurityListDesc=(").append(value).append(")")
}

object EncodedSecurityListDescField {
  val TagId = 1469  
  def decode(a: Option[Any]) : Option[EncodedSecurityListDescField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[EncodedSecurityListDescField]
  }

  def decode(a: Any) : Option[EncodedSecurityListDescField] = a match {
    case v: String => Some(EncodedSecurityListDescField(v))
    case v: EncodedSecurityListDescField => Some(v)
    case _ => scala.Option.empty[EncodedSecurityListDescField]
  } 
}
