package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldInt

/**
  * Generated by SackFix code generator on 20170521
  */
case class EncodedLegIssuerLenField(override val value: Int) extends SfFieldInt(618, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(618)EncodedLegIssuerLen=(").append(value).append(")")
}

object EncodedLegIssuerLenField {
  val TagId = 618  
  def apply(value: String) = try {
    new EncodedLegIssuerLenField(value.toInt)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new EncodedLegIssuerLen("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[EncodedLegIssuerLenField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[EncodedLegIssuerLenField]
  }

  def decode(a: Any) : Option[EncodedLegIssuerLenField] = a match {
    case v: String => Some(EncodedLegIssuerLenField(v))
    case v: Int => Some(EncodedLegIssuerLenField(v))
    case v: EncodedLegIssuerLenField => Some(v)
    case _ => scala.Option.empty[EncodedLegIssuerLenField]
  } 
}
