package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldInt

/**
  * Generated by SackFix code generator on 20210314
  */
case class EncryptedNewPasswordLenField(override val value: Int) extends SfFieldInt(1403, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(1403)EncryptedNewPasswordLen=(").append(value).append(")")
}

object EncryptedNewPasswordLenField {
  val TagId = 1403  
  def apply(value: String) = try {
    new EncryptedNewPasswordLenField(value.toInt)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new EncryptedNewPasswordLen("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[EncryptedNewPasswordLenField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[EncryptedNewPasswordLenField]
  }

  def decode(a: Any) : Option[EncryptedNewPasswordLenField] = a match {
    case v: String => Some(EncryptedNewPasswordLenField(v))
    case v: Int => Some(EncryptedNewPasswordLenField(v))
    case v: EncryptedNewPasswordLenField => Some(v)
    case _ => scala.Option.empty[EncryptedNewPasswordLenField]
  } 
}
