package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldBoolean

/**
  * Generated by SackFix code generator on 20210314
  */
case class ExchangeForPhysicalField(override val value: Boolean) extends SfFieldBoolean(411, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(411)ExchangeForPhysical=(").append({if (value) "Y" else "N"}).append(")")
}

object ExchangeForPhysicalField {
  val TagId = 411  
  def apply(value: String) = try {
    new ExchangeForPhysicalField(value match {
      case "Y" => true
      case "N" => false
      case _ => throw new IllegalArgumentException("ExchangeForPhysical.apply("+value+"] failed, bad value, expected Y or N.")
    })
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new ExchangeForPhysical("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[ExchangeForPhysicalField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[ExchangeForPhysicalField]
  }

  def decode(a: Any) : Option[ExchangeForPhysicalField] = a match {
    case v: String => Some(ExchangeForPhysicalField(v))
    case v: Boolean => Some(ExchangeForPhysicalField(v))
    case v: ExchangeForPhysicalField => Some(v)
    case _ => scala.Option.empty[ExchangeForPhysicalField]
  } 
}
