package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20170404
  */
case class ExecInstValueField(override val value: String) extends SfFieldString(1308, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(1308)ExecInstValue=(").append(value).append(")")
}

object ExecInstValueField {
  val TagId = 1308  
  def decode(a: Option[Any]) : Option[ExecInstValueField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[ExecInstValueField]
  }

  def decode(a: Any) : Option[ExecInstValueField] = a match {
    case v: String => Some(ExecInstValueField(v))
    case v: Char => Some(ExecInstValueField(v.toString))
    case v: ExecInstValueField => Some(v)
    case _ => scala.Option.empty[ExecInstValueField]
  } 
}
