package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldFloat

/**
  * Generated by SackFix code generator on 20210314
  */
case class ExecPriceAdjustmentField(override val value: Float) extends SfFieldFloat(485, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(485)ExecPriceAdjustment=(").append(value).append(")")
}

object ExecPriceAdjustmentField {
  val TagId = 485  
  def apply(value: String) = try {
    new ExecPriceAdjustmentField(value.toFloat)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new ExecPriceAdjustment("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[ExecPriceAdjustmentField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[ExecPriceAdjustmentField]
  }

  def decode(a: Any) : Option[ExecPriceAdjustmentField] = a match {
    case v: String => Some(ExecPriceAdjustmentField(v))
    case v: Float => Some(ExecPriceAdjustmentField(v))
    case v: Double => Some(ExecPriceAdjustmentField(v.toFloat))
    case v: Int => Some(ExecPriceAdjustmentField(v.toFloat))
    case v: ExecPriceAdjustmentField => Some(v)
    case _ => scala.Option.empty[ExecPriceAdjustmentField]
  } 
}
