package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldFloat

/**
  * Generated by SackFix code generator on 20170404
  */
case class FirstPxField(override val value: Float) extends SfFieldFloat(1025, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(1025)FirstPx=(").append(value).append(")")
}

object FirstPxField {
  val TagId = 1025  
  def apply(value: String) = try {
    new FirstPxField(value.toFloat)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new FirstPx("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[FirstPxField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[FirstPxField]
  }

  def decode(a: Any) : Option[FirstPxField] = a match {
    case v: String => Some(FirstPxField(v))
    case v: Float => Some(FirstPxField(v))
    case v: Double => Some(FirstPxField(v.toFloat))
    case v: Int => Some(FirstPxField(v.toFloat))
    case v: FirstPxField => Some(v)
    case _ => scala.Option.empty[FirstPxField]
  } 
}
