package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20210314
  */
case class InstrRegistryField(override val value: String) extends SfFieldString(543, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(543)InstrRegistry=(").append(value).append(")")
}

object InstrRegistryField {
  val TagId = 543  
  def decode(a: Option[Any]) : Option[InstrRegistryField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[InstrRegistryField]
  }

  def decode(a: Any) : Option[InstrRegistryField] = a match {
    case v: String => Some(InstrRegistryField(v))
    case v: InstrRegistryField => Some(v)
    case _ => scala.Option.empty[InstrRegistryField]
  } 
}
