package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20170521
  */
case class InstrumentPartySubIDField(override val value: String) extends SfFieldString(1053, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(1053)InstrumentPartySubID=(").append(value).append(")")
}

object InstrumentPartySubIDField {
  val TagId = 1053  
  def decode(a: Option[Any]) : Option[InstrumentPartySubIDField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[InstrumentPartySubIDField]
  }

  def decode(a: Any) : Option[InstrumentPartySubIDField] = a match {
    case v: String => Some(InstrumentPartySubIDField(v))
    case v: InstrumentPartySubIDField => Some(v)
    case _ => scala.Option.empty[InstrumentPartySubIDField]
  } 
}
