package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20210314
  */
case class IOITransTypeField(override val value: String) extends SfFieldString(28, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(28)IOITransType=(").append(value).append(")").append(IOITransTypeField.fixDescriptionByValue.getOrElse(value,""))
}

object IOITransTypeField {
  val TagId = 28 
  val New="N"
  val Cancel="C"
  val Replace="R"
  lazy val fixDescriptionByValue = Map("N"->"NEW","C"->"CANCEL",
    "R"->"REPLACE")
 
  def decode(a: Option[Any]) : Option[IOITransTypeField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[IOITransTypeField]
  }

  def decode(a: Any) : Option[IOITransTypeField] = a match {
    case v: String => Some(IOITransTypeField(v))
    case v: Char => Some(IOITransTypeField(v.toString))
    case v: IOITransTypeField => Some(v)
    case _ => scala.Option.empty[IOITransTypeField]
  } 
}
