package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldInt

/**
  * Generated by SackFix code generator on 20170521
  */
case class LastMsgSeqNumProcessedField(override val value: Int) extends SfFieldInt(369, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(369)LastMsgSeqNumProcessed=(").append(value).append(")")
}

object LastMsgSeqNumProcessedField {
  val TagId = 369  
  def apply(value: String) = try {
    new LastMsgSeqNumProcessedField(value.toInt)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new LastMsgSeqNumProcessed("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[LastMsgSeqNumProcessedField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[LastMsgSeqNumProcessedField]
  }

  def decode(a: Any) : Option[LastMsgSeqNumProcessedField] = a match {
    case v: String => Some(LastMsgSeqNumProcessedField(v))
    case v: Int => Some(LastMsgSeqNumProcessedField(v))
    case v: LastMsgSeqNumProcessedField => Some(v)
    case _ => scala.Option.empty[LastMsgSeqNumProcessedField]
  } 
}
