package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldFloat

/**
  * Generated by SackFix code generator on 20170404
  */
case class LastParPxField(override val value: Float) extends SfFieldFloat(669, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(669)LastParPx=(").append(value).append(")")
}

object LastParPxField {
  val TagId = 669  
  def apply(value: String) = try {
    new LastParPxField(value.toFloat)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new LastParPx("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[LastParPxField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[LastParPxField]
  }

  def decode(a: Any) : Option[LastParPxField] = a match {
    case v: String => Some(LastParPxField(v))
    case v: Float => Some(LastParPxField(v))
    case v: Double => Some(LastParPxField(v.toFloat))
    case v: Int => Some(LastParPxField(v.toFloat))
    case v: LastParPxField => Some(v)
    case _ => scala.Option.empty[LastParPxField]
  } 
}
