package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldFloat

/**
  * Generated by SackFix code generator on 20170521
  */
case class LegAllocQtyField(override val value: Float) extends SfFieldFloat(673, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(673)LegAllocQty=(").append(value).append(")")
}

object LegAllocQtyField {
  val TagId = 673  
  def apply(value: String) = try {
    new LegAllocQtyField(value.toFloat)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new LegAllocQty("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[LegAllocQtyField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[LegAllocQtyField]
  }

  def decode(a: Any) : Option[LegAllocQtyField] = a match {
    case v: String => Some(LegAllocQtyField(v))
    case v: Float => Some(LegAllocQtyField(v))
    case v: Double => Some(LegAllocQtyField(v.toFloat))
    case v: Int => Some(LegAllocQtyField(v.toFloat))
    case v: LegAllocQtyField => Some(v)
    case _ => scala.Option.empty[LegAllocQtyField]
  } 
}
