package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldBoolean

/**
  * Generated by SackFix code generator on 20170404
  */
case class LegalConfirmField(override val value: Boolean) extends SfFieldBoolean(650, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(650)LegalConfirm=(").append({if (value) "Y" else "N"}).append(")")
}

object LegalConfirmField {
  val TagId = 650  
  def apply(value: String) = try {
    new LegalConfirmField(value match {
      case "Y" => true
      case "N" => false
      case _ => throw new IllegalArgumentException("LegalConfirm.apply("+value+"] failed, bad value, expected Y or N.")
    })
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new LegalConfirm("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[LegalConfirmField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[LegalConfirmField]
  }

  def decode(a: Any) : Option[LegalConfirmField] = a match {
    case v: String => Some(LegalConfirmField(v))
    case v: Boolean => Some(LegalConfirmField(v))
    case v: LegalConfirmField => Some(v)
    case _ => scala.Option.empty[LegalConfirmField]
  } 
}
