package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldFloat

/**
  * Generated by SackFix code generator on 20170404
  */
case class LegBidPxField(override val value: Float) extends SfFieldFloat(681, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(681)LegBidPx=(").append(value).append(")")
}

object LegBidPxField {
  val TagId = 681  
  def apply(value: String) = try {
    new LegBidPxField(value.toFloat)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new LegBidPx("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[LegBidPxField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[LegBidPxField]
  }

  def decode(a: Any) : Option[LegBidPxField] = a match {
    case v: String => Some(LegBidPxField(v))
    case v: Float => Some(LegBidPxField(v))
    case v: Double => Some(LegBidPxField(v.toFloat))
    case v: Int => Some(LegBidPxField(v.toFloat))
    case v: LegBidPxField => Some(v)
    case _ => scala.Option.empty[LegBidPxField]
  } 
}
