package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20210314
  */
case class LegCountryOfIssueField(override val value: String) extends SfFieldString(596, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(596)LegCountryOfIssue=(").append(value).append(")")
}

object LegCountryOfIssueField {
  val TagId = 596  
  def decode(a: Option[Any]) : Option[LegCountryOfIssueField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[LegCountryOfIssueField]
  }

  def decode(a: Any) : Option[LegCountryOfIssueField] = a match {
    case v: String => Some(LegCountryOfIssueField(v))
    case v: LegCountryOfIssueField => Some(v)
    case _ => scala.Option.empty[LegCountryOfIssueField]
  } 
}
