package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldFloat

/**
  * Generated by SackFix code generator on 20170404
  */
case class LegFactorField(override val value: Float) extends SfFieldFloat(253, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(253)LegFactor=(").append(value).append(")")
}

object LegFactorField {
  val TagId = 253  
  def apply(value: String) = try {
    new LegFactorField(value.toFloat)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new LegFactor("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[LegFactorField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[LegFactorField]
  }

  def decode(a: Any) : Option[LegFactorField] = a match {
    case v: String => Some(LegFactorField(v))
    case v: Float => Some(LegFactorField(v))
    case v: Double => Some(LegFactorField(v.toFloat))
    case v: Int => Some(LegFactorField(v.toFloat))
    case v: LegFactorField => Some(v)
    case _ => scala.Option.empty[LegFactorField]
  } 
}
