package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldLocalMktDate
import java.time.LocalDate
import org.sackfix.common.validated.fields.SfFixDateFormats

/**
  * Generated by SackFix code generator on 20210314
  */
case class LegMaturityDateField(override val value: LocalDate) extends SfFieldLocalMktDate(611, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(611)LegMaturityDate=(").append(value).append(")")
}

object LegMaturityDateField {
  val TagId = 611  
  def apply(value: String) = try {
    new LegMaturityDateField(LocalDate.from(SfFixDateFormats.localMktDate.parse(value)))
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new LegMaturityDate("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[LegMaturityDateField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[LegMaturityDateField]
  }

  def decode(a: Any) : Option[LegMaturityDateField] = a match {
    case v: String => Some(LegMaturityDateField(v))
    case v: LocalDate => Some(LegMaturityDateField(v))
    case v: LegMaturityDateField => Some(v)
    case _ => scala.Option.empty[LegMaturityDateField]
  } 
}
