package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20170521
  */
case class LegOptAttributeField(override val value: String) extends SfFieldString(613, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(613)LegOptAttribute=(").append(value).append(")")
}

object LegOptAttributeField {
  val TagId = 613  
  def decode(a: Option[Any]) : Option[LegOptAttributeField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[LegOptAttributeField]
  }

  def decode(a: Any) : Option[LegOptAttributeField] = a match {
    case v: String => Some(LegOptAttributeField(v))
    case v: Char => Some(LegOptAttributeField(v.toString))
    case v: LegOptAttributeField => Some(v)
    case _ => scala.Option.empty[LegOptAttributeField]
  } 
}
