package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldFloat

/**
  * Generated by SackFix code generator on 20170404
  */
case class LegRepurchaseRateField(override val value: Float) extends SfFieldFloat(252, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(252)LegRepurchaseRate=(").append(value).append(")")
}

object LegRepurchaseRateField {
  val TagId = 252  
  def apply(value: String) = try {
    new LegRepurchaseRateField(value.toFloat)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new LegRepurchaseRate("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[LegRepurchaseRateField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[LegRepurchaseRateField]
  }

  def decode(a: Any) : Option[LegRepurchaseRateField] = a match {
    case v: String => Some(LegRepurchaseRateField(v))
    case v: Float => Some(LegRepurchaseRateField(v))
    case v: Double => Some(LegRepurchaseRateField(v.toFloat))
    case v: Int => Some(LegRepurchaseRateField(v.toFloat))
    case v: LegRepurchaseRateField => Some(v)
    case _ => scala.Option.empty[LegRepurchaseRateField]
  } 
}
