package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldLocalMktDate
import java.time.LocalDate
import org.sackfix.common.validated.fields.SfFixDateFormats

/**
  * Generated by SackFix code generator on 20170404
  */
case class LegRedemptionDateField(override val value: LocalDate) extends SfFieldLocalMktDate(254, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(254)LegRedemptionDate=(").append(value).append(")")
}

object LegRedemptionDateField {
  val TagId = 254  
  def apply(value: String) = try {
    new LegRedemptionDateField(LocalDate.from(SfFixDateFormats.localMktDate.parse(value)))
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new LegRedemptionDate("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[LegRedemptionDateField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[LegRedemptionDateField]
  }

  def decode(a: Any) : Option[LegRedemptionDateField] = a match {
    case v: String => Some(LegRedemptionDateField(v))
    case v: LocalDate => Some(LegRedemptionDateField(v))
    case v: LegRedemptionDateField => Some(v)
    case _ => scala.Option.empty[LegRedemptionDateField]
  } 
}
