package org.sackfix.field

import org.sackfix.common.validated.fields.SfNumInGroup

/**
  * Generated by SackFix code generator on 20170404
  */
case class LinesOfTextField(override val value: Int) extends SfNumInGroup(33, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(33)LinesOfText=(").append(value).append(")")
}

object LinesOfTextField {
  val TagId = 33  
  def apply(value: String) = try {
    new LinesOfTextField(value.toInt)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new LinesOfText("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[LinesOfTextField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[LinesOfTextField]
  }

  def decode(a: Any) : Option[LinesOfTextField] = a match {
    case v: String => Some(LinesOfTextField(v))
    case v: Int => Some(LinesOfTextField(v))
    case v: LinesOfTextField => Some(v)
    case _ => scala.Option.empty[LinesOfTextField]
  } 
}
