package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldFloat

/**
  * Generated by SackFix code generator on 20170521
  */
case class LiquidityPctLowField(override val value: Float) extends SfFieldFloat(402, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(402)LiquidityPctLow=(").append(value).append(")")
}

object LiquidityPctLowField {
  val TagId = 402  
  def apply(value: String) = try {
    new LiquidityPctLowField(value.toFloat)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new LiquidityPctLow("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[LiquidityPctLowField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[LiquidityPctLowField]
  }

  def decode(a: Any) : Option[LiquidityPctLowField] = a match {
    case v: String => Some(LiquidityPctLowField(v))
    case v: Float => Some(LiquidityPctLowField(v))
    case v: Double => Some(LiquidityPctLowField(v.toFloat))
    case v: Int => Some(LiquidityPctLowField(v.toFloat))
    case v: LiquidityPctLowField => Some(v)
    case _ => scala.Option.empty[LiquidityPctLowField]
  } 
}
