package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20170521
  */
case class ListStatusTextField(override val value: String) extends SfFieldString(444, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(444)ListStatusText=(").append(value).append(")")
}

object ListStatusTextField {
  val TagId = 444  
  def decode(a: Option[Any]) : Option[ListStatusTextField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[ListStatusTextField]
  }

  def decode(a: Any) : Option[ListStatusTextField] = a match {
    case v: String => Some(ListStatusTextField(v))
    case v: ListStatusTextField => Some(v)
    case _ => scala.Option.empty[ListStatusTextField]
  } 
}
