package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldInt

/**
  * Generated by SackFix code generator on 20170521
  */
case class ListMethodField(override val value: Int) extends SfFieldInt(1198, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(1198)ListMethod=(").append(value).append(")").append(ListMethodField.fixDescriptionByValue.getOrElse(value,""))
}

object ListMethodField {
  val TagId = 1198 
  val PreListedOnly=0
  val UserRequested=1
  lazy val fixDescriptionByValue = Map(0->"PRE_LISTED_ONLY",1->"USER_REQUESTED")
 
  def apply(value: String) = try {
    new ListMethodField(value.toInt)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new ListMethod("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[ListMethodField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[ListMethodField]
  }

  def decode(a: Any) : Option[ListMethodField] = a match {
    case v: String => Some(ListMethodField(v))
    case v: Int => Some(ListMethodField(v))
    case v: ListMethodField => Some(v)
    case _ => scala.Option.empty[ListMethodField]
  } 
}
