package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20210314
  */
case class MailingDtlsField(override val value: String) extends SfFieldString(474, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(474)MailingDtls=(").append(value).append(")")
}

object MailingDtlsField {
  val TagId = 474  
  def decode(a: Option[Any]) : Option[MailingDtlsField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[MailingDtlsField]
  }

  def decode(a: Any) : Option[MailingDtlsField] = a match {
    case v: String => Some(MailingDtlsField(v))
    case v: MailingDtlsField => Some(v)
    case _ => scala.Option.empty[MailingDtlsField]
  } 
}
