package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldInt

/**
  * Generated by SackFix code generator on 20210314
  */
case class MassActionTypeField(override val value: Int) extends SfFieldInt(1373, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(1373)MassActionType=(").append(value).append(")").append(MassActionTypeField.fixDescriptionByValue.getOrElse(value,""))
}

object MassActionTypeField {
  val TagId = 1373 
  val SuspendOrders=1
  val ReleaseOrdersFromSuspension=2
  val CancelOrders=3
  lazy val fixDescriptionByValue = Map(1->"SUSPEND_ORDERS",2->"RELEASE_ORDERS_FROM_SUSPENSION",
    3->"CANCEL_ORDERS")
 
  def apply(value: String) = try {
    new MassActionTypeField(value.toInt)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new MassActionType("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[MassActionTypeField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[MassActionTypeField]
  }

  def decode(a: Any) : Option[MassActionTypeField] = a match {
    case v: String => Some(MassActionTypeField(v))
    case v: Int => Some(MassActionTypeField(v))
    case v: MassActionTypeField => Some(v)
    case _ => scala.Option.empty[MassActionTypeField]
  } 
}
