package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldFloat

/**
  * Generated by SackFix code generator on 20170521
  */
case class MatchIncrementField(override val value: Float) extends SfFieldFloat(1089, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(1089)MatchIncrement=(").append(value).append(")")
}

object MatchIncrementField {
  val TagId = 1089  
  def apply(value: String) = try {
    new MatchIncrementField(value.toFloat)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new MatchIncrement("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[MatchIncrementField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[MatchIncrementField]
  }

  def decode(a: Any) : Option[MatchIncrementField] = a match {
    case v: String => Some(MatchIncrementField(v))
    case v: Float => Some(MatchIncrementField(v))
    case v: Double => Some(MatchIncrementField(v.toFloat))
    case v: Int => Some(MatchIncrementField(v.toFloat))
    case v: MatchIncrementField => Some(v)
    case _ => scala.Option.empty[MatchIncrementField]
  } 
}
