package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldInt

/**
  * Generated by SackFix code generator on 20210314
  */
case class MDPriceLevelField(override val value: Int) extends SfFieldInt(1023, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(1023)MDPriceLevel=(").append(value).append(")")
}

object MDPriceLevelField {
  val TagId = 1023  
  def apply(value: String) = try {
    new MDPriceLevelField(value.toInt)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new MDPriceLevel("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[MDPriceLevelField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[MDPriceLevelField]
  }

  def decode(a: Any) : Option[MDPriceLevelField] = a match {
    case v: String => Some(MDPriceLevelField(v))
    case v: Int => Some(MDPriceLevelField(v))
    case v: MDPriceLevelField => Some(v)
    case _ => scala.Option.empty[MDPriceLevelField]
  } 
}
