package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20170404
  */
case class MDReqIDField(override val value: String) extends SfFieldString(262, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(262)MDReqID=(").append(value).append(")")
}

object MDReqIDField {
  val TagId = 262  
  def decode(a: Option[Any]) : Option[MDReqIDField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[MDReqIDField]
  }

  def decode(a: Any) : Option[MDReqIDField] = a match {
    case v: String => Some(MDReqIDField(v))
    case v: MDReqIDField => Some(v)
    case _ => scala.Option.empty[MDReqIDField]
  } 
}
