package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldInt

/**
  * Generated by SackFix code generator on 20170521
  */
case class MsgSeqNumField(override val value: Int) extends SfFieldInt(34, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(34)MsgSeqNum=(").append(value).append(")")
}

object MsgSeqNumField {
  val TagId = 34  
  def apply(value: String) = try {
    new MsgSeqNumField(value.toInt)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new MsgSeqNum("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[MsgSeqNumField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[MsgSeqNumField]
  }

  def decode(a: Any) : Option[MsgSeqNumField] = a match {
    case v: String => Some(MsgSeqNumField(v))
    case v: Int => Some(MsgSeqNumField(v))
    case v: MsgSeqNumField => Some(v)
    case _ => scala.Option.empty[MsgSeqNumField]
  } 
}
