package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldInt

/**
  * Generated by SackFix code generator on 20170521
  */
case class Nested4PartyRoleField(override val value: Int) extends SfFieldInt(1417, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(1417)Nested4PartyRole=(").append(value).append(")")
}

object Nested4PartyRoleField {
  val TagId = 1417  
  def apply(value: String) = try {
    new Nested4PartyRoleField(value.toInt)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new Nested4PartyRole("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[Nested4PartyRoleField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[Nested4PartyRoleField]
  }

  def decode(a: Any) : Option[Nested4PartyRoleField] = a match {
    case v: String => Some(Nested4PartyRoleField(v))
    case v: Int => Some(Nested4PartyRoleField(v))
    case v: Nested4PartyRoleField => Some(v)
    case _ => scala.Option.empty[Nested4PartyRoleField]
  } 
}
