package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldInt

/**
  * Generated by SackFix code generator on 20170404
  */
case class Nested3PartySubIDTypeField(override val value: Int) extends SfFieldInt(954, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(954)Nested3PartySubIDType=(").append(value).append(")")
}

object Nested3PartySubIDTypeField {
  val TagId = 954  
  def apply(value: String) = try {
    new Nested3PartySubIDTypeField(value.toInt)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new Nested3PartySubIDType("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[Nested3PartySubIDTypeField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[Nested3PartySubIDTypeField]
  }

  def decode(a: Any) : Option[Nested3PartySubIDTypeField] = a match {
    case v: String => Some(Nested3PartySubIDTypeField(v))
    case v: Int => Some(Nested3PartySubIDTypeField(v))
    case v: Nested3PartySubIDTypeField => Some(v)
    case _ => scala.Option.empty[Nested3PartySubIDTypeField]
  } 
}
