package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldInt

/**
  * Generated by SackFix code generator on 20210314
  */
case class NestedPartyRoleField(override val value: Int) extends SfFieldInt(538, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(538)NestedPartyRole=(").append(value).append(")")
}

object NestedPartyRoleField {
  val TagId = 538  
  def apply(value: String) = try {
    new NestedPartyRoleField(value.toInt)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new NestedPartyRole("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[NestedPartyRoleField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[NestedPartyRoleField]
  }

  def decode(a: Any) : Option[NestedPartyRoleField] = a match {
    case v: String => Some(NestedPartyRoleField(v))
    case v: Int => Some(NestedPartyRoleField(v))
    case v: NestedPartyRoleField => Some(v)
    case _ => scala.Option.empty[NestedPartyRoleField]
  } 
}
