package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20170404
  */
case class NewsRefIDField(override val value: String) extends SfFieldString(1476, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(1476)NewsRefID=(").append(value).append(")")
}

object NewsRefIDField {
  val TagId = 1476  
  def decode(a: Option[Any]) : Option[NewsRefIDField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[NewsRefIDField]
  }

  def decode(a: Any) : Option[NewsRefIDField] = a match {
    case v: String => Some(NewsRefIDField(v))
    case v: NewsRefIDField => Some(v)
    case _ => scala.Option.empty[NewsRefIDField]
  } 
}
