package org.sackfix.field

import org.sackfix.common.validated.fields.SfNumInGroup

/**
  * Generated by SackFix code generator on 20210314
  */
case class NoAltMDSourceField(override val value: Int) extends SfNumInGroup(816, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(816)NoAltMDSource=(").append(value).append(")")
}

object NoAltMDSourceField {
  val TagId = 816  
  def apply(value: String) = try {
    new NoAltMDSourceField(value.toInt)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new NoAltMDSource("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[NoAltMDSourceField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[NoAltMDSourceField]
  }

  def decode(a: Any) : Option[NoAltMDSourceField] = a match {
    case v: String => Some(NoAltMDSourceField(v))
    case v: Int => Some(NoAltMDSourceField(v))
    case v: NoAltMDSourceField => Some(v)
    case _ => scala.Option.empty[NoAltMDSourceField]
  } 
}
