package org.sackfix.field

import org.sackfix.common.validated.fields.SfNumInGroup

/**
  * Generated by SackFix code generator on 20210314
  */
case class NoAllocsField(override val value: Int) extends SfNumInGroup(78, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(78)NoAllocs=(").append(value).append(")")
}

object NoAllocsField {
  val TagId = 78  
  def apply(value: String) = try {
    new NoAllocsField(value.toInt)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new NoAllocs("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[NoAllocsField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[NoAllocsField]
  }

  def decode(a: Any) : Option[NoAllocsField] = a match {
    case v: String => Some(NoAllocsField(v))
    case v: Int => Some(NoAllocsField(v))
    case v: NoAllocsField => Some(v)
    case _ => scala.Option.empty[NoAllocsField]
  } 
}
