package org.sackfix.field

import org.sackfix.common.validated.fields.SfNumInGroup

/**
  * Generated by SackFix code generator on 20210314
  */
case class NoAsgnReqsField(override val value: Int) extends SfNumInGroup(1499, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(1499)NoAsgnReqs=(").append(value).append(")")
}

object NoAsgnReqsField {
  val TagId = 1499  
  def apply(value: String) = try {
    new NoAsgnReqsField(value.toInt)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new NoAsgnReqs("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[NoAsgnReqsField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[NoAsgnReqsField]
  }

  def decode(a: Any) : Option[NoAsgnReqsField] = a match {
    case v: String => Some(NoAsgnReqsField(v))
    case v: Int => Some(NoAsgnReqsField(v))
    case v: NoAsgnReqsField => Some(v)
    case _ => scala.Option.empty[NoAsgnReqsField]
  } 
}
