package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20170404
  */
case class NoLegSecurityAltIDStringField(override val value: String) extends SfFieldString(604, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(604)NoLegSecurityAltIDString=(").append(value).append(")")
}

object NoLegSecurityAltIDStringField {
  val TagId = 604  
  def decode(a: Option[Any]) : Option[NoLegSecurityAltIDStringField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[NoLegSecurityAltIDStringField]
  }

  def decode(a: Any) : Option[NoLegSecurityAltIDStringField] = a match {
    case v: String => Some(NoLegSecurityAltIDStringField(v))
    case v: NoLegSecurityAltIDStringField => Some(v)
    case _ => scala.Option.empty[NoLegSecurityAltIDStringField]
  } 
}
