package org.sackfix.field

import org.sackfix.common.validated.fields.SfNumInGroup

/**
  * Generated by SackFix code generator on 20210314
  */
case class NoNested3PartyIDsField(override val value: Int) extends SfNumInGroup(948, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(948)NoNested3PartyIDs=(").append(value).append(")")
}

object NoNested3PartyIDsField {
  val TagId = 948  
  def apply(value: String) = try {
    new NoNested3PartyIDsField(value.toInt)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new NoNested3PartyIDs("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[NoNested3PartyIDsField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[NoNested3PartyIDsField]
  }

  def decode(a: Any) : Option[NoNested3PartyIDsField] = a match {
    case v: String => Some(NoNested3PartyIDsField(v))
    case v: Int => Some(NoNested3PartyIDsField(v))
    case v: NoNested3PartyIDsField => Some(v)
    case _ => scala.Option.empty[NoNested3PartyIDsField]
  } 
}
