package org.sackfix.field

import org.sackfix.common.validated.fields.SfNumInGroup

/**
  * Generated by SackFix code generator on 20210314
  */
case class NoNested2PartySubIDsField(override val value: Int) extends SfNumInGroup(806, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(806)NoNested2PartySubIDs=(").append(value).append(")")
}

object NoNested2PartySubIDsField {
  val TagId = 806  
  def apply(value: String) = try {
    new NoNested2PartySubIDsField(value.toInt)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new NoNested2PartySubIDs("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[NoNested2PartySubIDsField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[NoNested2PartySubIDsField]
  }

  def decode(a: Any) : Option[NoNested2PartySubIDsField] = a match {
    case v: String => Some(NoNested2PartySubIDsField(v))
    case v: Int => Some(NoNested2PartySubIDsField(v))
    case v: NoNested2PartySubIDsField => Some(v)
    case _ => scala.Option.empty[NoNested2PartySubIDsField]
  } 
}
