package org.sackfix.field

import org.sackfix.common.validated.fields.SfNumInGroup

/**
  * Generated by SackFix code generator on 20210314
  */
case class NoNested4PartySubIDsField(override val value: Int) extends SfNumInGroup(1413, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(1413)NoNested4PartySubIDs=(").append(value).append(")")
}

object NoNested4PartySubIDsField {
  val TagId = 1413  
  def apply(value: String) = try {
    new NoNested4PartySubIDsField(value.toInt)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new NoNested4PartySubIDs("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[NoNested4PartySubIDsField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[NoNested4PartySubIDsField]
  }

  def decode(a: Any) : Option[NoNested4PartySubIDsField] = a match {
    case v: String => Some(NoNested4PartySubIDsField(v))
    case v: Int => Some(NoNested4PartySubIDsField(v))
    case v: NoNested4PartySubIDsField => Some(v)
    case _ => scala.Option.empty[NoNested4PartySubIDsField]
  } 
}
