package org.sackfix.field

import org.sackfix.common.validated.fields.SfNumInGroup

/**
  * Generated by SackFix code generator on 20210314
  */
case class NoNestedInstrAttribField(override val value: Int) extends SfNumInGroup(1312, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(1312)NoNestedInstrAttrib=(").append(value).append(")")
}

object NoNestedInstrAttribField {
  val TagId = 1312  
  def apply(value: String) = try {
    new NoNestedInstrAttribField(value.toInt)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new NoNestedInstrAttrib("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[NoNestedInstrAttribField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[NoNestedInstrAttribField]
  }

  def decode(a: Any) : Option[NoNestedInstrAttribField] = a match {
    case v: String => Some(NoNestedInstrAttribField(v))
    case v: Int => Some(NoNestedInstrAttribField(v))
    case v: NoNestedInstrAttribField => Some(v)
    case _ => scala.Option.empty[NoNestedInstrAttribField]
  } 
}
