package org.sackfix.field

import org.sackfix.common.validated.fields.SfNumInGroup

/**
  * Generated by SackFix code generator on 20170404
  */
case class NoPartyIDsField(override val value: Int) extends SfNumInGroup(453, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(453)NoPartyIDs=(").append(value).append(")")
}

object NoPartyIDsField {
  val TagId = 453  
  def apply(value: String) = try {
    new NoPartyIDsField(value.toInt)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new NoPartyIDs("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[NoPartyIDsField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[NoPartyIDsField]
  }

  def decode(a: Any) : Option[NoPartyIDsField] = a match {
    case v: String => Some(NoPartyIDsField(v))
    case v: Int => Some(NoPartyIDsField(v))
    case v: NoPartyIDsField => Some(v)
    case _ => scala.Option.empty[NoPartyIDsField]
  } 
}
