package org.sackfix.field

import org.sackfix.common.validated.fields.SfNumInGroup

/**
  * Generated by SackFix code generator on 20210314
  */
case class NoQuoteEntriesField(override val value: Int) extends SfNumInGroup(295, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(295)NoQuoteEntries=(").append(value).append(")")
}

object NoQuoteEntriesField {
  val TagId = 295  
  def apply(value: String) = try {
    new NoQuoteEntriesField(value.toInt)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new NoQuoteEntries("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[NoQuoteEntriesField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[NoQuoteEntriesField]
  }

  def decode(a: Any) : Option[NoQuoteEntriesField] = a match {
    case v: String => Some(NoQuoteEntriesField(v))
    case v: Int => Some(NoQuoteEntriesField(v))
    case v: NoQuoteEntriesField => Some(v)
    case _ => scala.Option.empty[NoQuoteEntriesField]
  } 
}
