package org.sackfix.field

import org.sackfix.common.validated.fields.SfNumInGroup

/**
  * Generated by SackFix code generator on 20170521
  */
case class NoRootPartyIDsField(override val value: Int) extends SfNumInGroup(1116, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(1116)NoRootPartyIDs=(").append(value).append(")")
}

object NoRootPartyIDsField {
  val TagId = 1116  
  def apply(value: String) = try {
    new NoRootPartyIDsField(value.toInt)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new NoRootPartyIDs("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[NoRootPartyIDsField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[NoRootPartyIDsField]
  }

  def decode(a: Any) : Option[NoRootPartyIDsField] = a match {
    case v: String => Some(NoRootPartyIDsField(v))
    case v: Int => Some(NoRootPartyIDsField(v))
    case v: NoRootPartyIDsField => Some(v)
    case _ => scala.Option.empty[NoRootPartyIDsField]
  } 
}
