package org.sackfix.field

import org.sackfix.common.validated.fields.SfNumInGroup

/**
  * Generated by SackFix code generator on 20170521
  */
case class NoStrategyParametersField(override val value: Int) extends SfNumInGroup(957, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(957)NoStrategyParameters=(").append(value).append(")")
}

object NoStrategyParametersField {
  val TagId = 957  
  def apply(value: String) = try {
    new NoStrategyParametersField(value.toInt)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new NoStrategyParameters("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[NoStrategyParametersField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[NoStrategyParametersField]
  }

  def decode(a: Any) : Option[NoStrategyParametersField] = a match {
    case v: String => Some(NoStrategyParametersField(v))
    case v: Int => Some(NoStrategyParametersField(v))
    case v: NoStrategyParametersField => Some(v)
    case _ => scala.Option.empty[NoStrategyParametersField]
  } 
}
