package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldUtcTimeStamp
import java.time.LocalDateTime
import org.sackfix.common.validated.fields.SfFixDateFormats

/**
  * Generated by SackFix code generator on 20210314
  */
case class OnBehalfOfSendingTimeField(override val value: LocalDateTime) extends SfFieldUtcTimeStamp(370, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(370)OnBehalfOfSendingTime=(").append(value).append(")")
}

object OnBehalfOfSendingTimeField {
  val TagId = 370  
  def apply(value: String) = try {
    new OnBehalfOfSendingTimeField(LocalDateTime.from(SfFixDateFormats.utcTimeStamp.parse(value)))
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new OnBehalfOfSendingTime("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[OnBehalfOfSendingTimeField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[OnBehalfOfSendingTimeField]
  }

  def decode(a: Any) : Option[OnBehalfOfSendingTimeField] = a match {
    case v: String => Some(OnBehalfOfSendingTimeField(v))
    case v: LocalDateTime => Some(OnBehalfOfSendingTimeField(v))
    case v: OnBehalfOfSendingTimeField => Some(v)
    case _ => scala.Option.empty[OnBehalfOfSendingTimeField]
  } 
}
