package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldFloat

/**
  * Generated by SackFix code generator on 20210314
  */
case class OrderPercentField(override val value: Float) extends SfFieldFloat(516, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(516)OrderPercent=(").append(value).append(")")
}

object OrderPercentField {
  val TagId = 516  
  def apply(value: String) = try {
    new OrderPercentField(value.toFloat)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new OrderPercent("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[OrderPercentField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[OrderPercentField]
  }

  def decode(a: Any) : Option[OrderPercentField] = a match {
    case v: String => Some(OrderPercentField(v))
    case v: Float => Some(OrderPercentField(v))
    case v: Double => Some(OrderPercentField(v.toFloat))
    case v: Int => Some(OrderPercentField(v.toFloat))
    case v: OrderPercentField => Some(v)
    case _ => scala.Option.empty[OrderPercentField]
  } 
}
