package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldInt

/**
  * Generated by SackFix code generator on 20210314
  */
case class OrderHandlingInstSourceField(override val value: Int) extends SfFieldInt(1032, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(1032)OrderHandlingInstSource=(").append(value).append(")").append(OrderHandlingInstSourceField.fixDescriptionByValue.getOrElse(value,""))
}

object OrderHandlingInstSourceField {
  val TagId = 1032 
  val NasdOats=1
  lazy val fixDescriptionByValue = Map(1->"NASD_OATS")
 
  def apply(value: String) = try {
    new OrderHandlingInstSourceField(value.toInt)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new OrderHandlingInstSource("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[OrderHandlingInstSourceField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[OrderHandlingInstSourceField]
  }

  def decode(a: Any) : Option[OrderHandlingInstSourceField] = a match {
    case v: String => Some(OrderHandlingInstSourceField(v))
    case v: Int => Some(OrderHandlingInstSourceField(v))
    case v: OrderHandlingInstSourceField => Some(v)
    case _ => scala.Option.empty[OrderHandlingInstSourceField]
  } 
}
