package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20210314
  */
case class OrigCrossIDField(override val value: String) extends SfFieldString(551, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(551)OrigCrossID=(").append(value).append(")")
}

object OrigCrossIDField {
  val TagId = 551  
  def decode(a: Option[Any]) : Option[OrigCrossIDField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[OrigCrossIDField]
  }

  def decode(a: Any) : Option[OrigCrossIDField] = a match {
    case v: String => Some(OrigCrossIDField(v))
    case v: OrigCrossIDField => Some(v)
    case _ => scala.Option.empty[OrigCrossIDField]
  } 
}
