package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldFloat

/**
  * Generated by SackFix code generator on 20210314
  */
case class OutsideIndexPctField(override val value: Float) extends SfFieldFloat(407, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(407)OutsideIndexPct=(").append(value).append(")")
}

object OutsideIndexPctField {
  val TagId = 407  
  def apply(value: String) = try {
    new OutsideIndexPctField(value.toFloat)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new OutsideIndexPct("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[OutsideIndexPctField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[OutsideIndexPctField]
  }

  def decode(a: Any) : Option[OutsideIndexPctField] = a match {
    case v: String => Some(OutsideIndexPctField(v))
    case v: Float => Some(OutsideIndexPctField(v))
    case v: Double => Some(OutsideIndexPctField(v.toFloat))
    case v: Int => Some(OutsideIndexPctField(v.toFloat))
    case v: OutsideIndexPctField => Some(v)
    case _ => scala.Option.empty[OutsideIndexPctField]
  } 
}
