package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20210314
  */
case class PartyIDField(override val value: String) extends SfFieldString(448, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(448)PartyID=(").append(value).append(")")
}

object PartyIDField {
  val TagId = 448  
  def decode(a: Option[Any]) : Option[PartyIDField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[PartyIDField]
  }

  def decode(a: Any) : Option[PartyIDField] = a match {
    case v: String => Some(PartyIDField(v))
    case v: PartyIDField => Some(v)
    case _ => scala.Option.empty[PartyIDField]
  } 
}
