package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldFloat

/**
  * Generated by SackFix code generator on 20170404
  */
case class PrevClosePxField(override val value: Float) extends SfFieldFloat(140, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(140)PrevClosePx=(").append(value).append(")")
}

object PrevClosePxField {
  val TagId = 140  
  def apply(value: String) = try {
    new PrevClosePxField(value.toFloat)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new PrevClosePx("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[PrevClosePxField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[PrevClosePxField]
  }

  def decode(a: Any) : Option[PrevClosePxField] = a match {
    case v: String => Some(PrevClosePxField(v))
    case v: Float => Some(PrevClosePxField(v))
    case v: Double => Some(PrevClosePxField(v.toFloat))
    case v: Int => Some(PrevClosePxField(v.toFloat))
    case v: PrevClosePxField => Some(v)
    case _ => scala.Option.empty[PrevClosePxField]
  } 
}
