package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldFloat

/**
  * Generated by SackFix code generator on 20170521
  */
case class PriceDeltaField(override val value: Float) extends SfFieldFloat(811, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(811)PriceDelta=(").append(value).append(")")
}

object PriceDeltaField {
  val TagId = 811  
  def apply(value: String) = try {
    new PriceDeltaField(value.toFloat)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new PriceDelta("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[PriceDeltaField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[PriceDeltaField]
  }

  def decode(a: Any) : Option[PriceDeltaField] = a match {
    case v: String => Some(PriceDeltaField(v))
    case v: Float => Some(PriceDeltaField(v))
    case v: Double => Some(PriceDeltaField(v.toFloat))
    case v: Int => Some(PriceDeltaField(v.toFloat))
    case v: PriceDeltaField => Some(v)
    case _ => scala.Option.empty[PriceDeltaField]
  } 
}
