package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldFloat

/**
  * Generated by SackFix code generator on 20170404
  */
case class Price2Field(override val value: Float) extends SfFieldFloat(640, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(640)Price2=(").append(value).append(")")
}

object Price2Field {
  val TagId = 640  
  def apply(value: String) = try {
    new Price2Field(value.toFloat)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new Price2("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[Price2Field] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[Price2Field]
  }

  def decode(a: Any) : Option[Price2Field] = a match {
    case v: String => Some(Price2Field(v))
    case v: Float => Some(Price2Field(v))
    case v: Double => Some(Price2Field(v.toFloat))
    case v: Int => Some(Price2Field(v.toFloat))
    case v: Price2Field => Some(v)
    case _ => scala.Option.empty[Price2Field]
  } 
}
