package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldInt

/**
  * Generated by SackFix code generator on 20170404
  */
case class RefApplLastSeqNumField(override val value: Int) extends SfFieldInt(1357, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(1357)RefApplLastSeqNum=(").append(value).append(")")
}

object RefApplLastSeqNumField {
  val TagId = 1357  
  def apply(value: String) = try {
    new RefApplLastSeqNumField(value.toInt)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new RefApplLastSeqNum("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[RefApplLastSeqNumField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[RefApplLastSeqNumField]
  }

  def decode(a: Any) : Option[RefApplLastSeqNumField] = a match {
    case v: String => Some(RefApplLastSeqNumField(v))
    case v: Int => Some(RefApplLastSeqNumField(v))
    case v: RefApplLastSeqNumField => Some(v)
    case _ => scala.Option.empty[RefApplLastSeqNumField]
  } 
}
