package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20170404
  */
case class RegistAcctTypeField(override val value: String) extends SfFieldString(493, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(493)RegistAcctType=(").append(value).append(")")
}

object RegistAcctTypeField {
  val TagId = 493  
  def decode(a: Option[Any]) : Option[RegistAcctTypeField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[RegistAcctTypeField]
  }

  def decode(a: Any) : Option[RegistAcctTypeField] = a match {
    case v: String => Some(RegistAcctTypeField(v))
    case v: RegistAcctTypeField => Some(v)
    case _ => scala.Option.empty[RegistAcctTypeField]
  } 
}
