package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20170404
  */
case class RegistIDField(override val value: String) extends SfFieldString(513, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(513)RegistID=(").append(value).append(")")
}

object RegistIDField {
  val TagId = 513  
  def decode(a: Option[Any]) : Option[RegistIDField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[RegistIDField]
  }

  def decode(a: Any) : Option[RegistIDField] = a match {
    case v: String => Some(RegistIDField(v))
    case v: RegistIDField => Some(v)
    case _ => scala.Option.empty[RegistIDField]
  } 
}
