package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20210314
  */
case class ReportToExchStringField(override val value: String) extends SfFieldString(113, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(113)ReportToExchString=(").append(value).append(")")
}

object ReportToExchStringField {
  val TagId = 113  
  def decode(a: Option[Any]) : Option[ReportToExchStringField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[ReportToExchStringField]
  }

  def decode(a: Any) : Option[ReportToExchStringField] = a match {
    case v: String => Some(ReportToExchStringField(v))
    case v: ReportToExchStringField => Some(v)
    case _ => scala.Option.empty[ReportToExchStringField]
  } 
}
