package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20210314
  */
case class RootPartyIDSourceField(override val value: String) extends SfFieldString(1118, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(1118)RootPartyIDSource=(").append(value).append(")")
}

object RootPartyIDSourceField {
  val TagId = 1118  
  def decode(a: Option[Any]) : Option[RootPartyIDSourceField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[RootPartyIDSourceField]
  }

  def decode(a: Any) : Option[RootPartyIDSourceField] = a match {
    case v: String => Some(RootPartyIDSourceField(v))
    case v: Char => Some(RootPartyIDSourceField(v.toString))
    case v: RootPartyIDSourceField => Some(v)
    case _ => scala.Option.empty[RootPartyIDSourceField]
  } 
}
