package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldInt

/**
  * Generated by SackFix code generator on 20170521
  */
case class RootPartyRoleField(override val value: Int) extends SfFieldInt(1119, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(1119)RootPartyRole=(").append(value).append(")")
}

object RootPartyRoleField {
  val TagId = 1119  
  def apply(value: String) = try {
    new RootPartyRoleField(value.toInt)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new RootPartyRole("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[RootPartyRoleField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[RootPartyRoleField]
  }

  def decode(a: Any) : Option[RootPartyRoleField] = a match {
    case v: String => Some(RootPartyRoleField(v))
    case v: Int => Some(RootPartyRoleField(v))
    case v: RootPartyRoleField => Some(v)
    case _ => scala.Option.empty[RootPartyRoleField]
  } 
}
