package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldInt

/**
  * Generated by SackFix code generator on 20210314
  */
case class RptSeqField(override val value: Int) extends SfFieldInt(83, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(83)RptSeq=(").append(value).append(")")
}

object RptSeqField {
  val TagId = 83  
  def apply(value: String) = try {
    new RptSeqField(value.toInt)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new RptSeq("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[RptSeqField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[RptSeqField]
  }

  def decode(a: Any) : Option[RptSeqField] = a match {
    case v: String => Some(RptSeqField(v))
    case v: Int => Some(RptSeqField(v))
    case v: RptSeqField => Some(v)
    case _ => scala.Option.empty[RptSeqField]
  } 
}
