package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldInt

/**
  * Generated by SackFix code generator on 20210314
  */
case class SecondaryTrdTypeField(override val value: Int) extends SfFieldInt(855, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(855)SecondaryTrdType=(").append(value).append(")")
}

object SecondaryTrdTypeField {
  val TagId = 855  
  def apply(value: String) = try {
    new SecondaryTrdTypeField(value.toInt)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new SecondaryTrdType("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[SecondaryTrdTypeField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[SecondaryTrdTypeField]
  }

  def decode(a: Any) : Option[SecondaryTrdTypeField] = a match {
    case v: String => Some(SecondaryTrdTypeField(v))
    case v: Int => Some(SecondaryTrdTypeField(v))
    case v: SecondaryTrdTypeField => Some(v)
    case _ => scala.Option.empty[SecondaryTrdTypeField]
  } 
}
