package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20170521
  */
case class SecondaryExecIDField(override val value: String) extends SfFieldString(527, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(527)SecondaryExecID=(").append(value).append(")")
}

object SecondaryExecIDField {
  val TagId = 527  
  def decode(a: Option[Any]) : Option[SecondaryExecIDField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[SecondaryExecIDField]
  }

  def decode(a: Any) : Option[SecondaryExecIDField] = a match {
    case v: String => Some(SecondaryExecIDField(v))
    case v: SecondaryExecIDField => Some(v)
    case _ => scala.Option.empty[SecondaryExecIDField]
  } 
}
