package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20170404
  */
case class SecurityIDField(override val value: String) extends SfFieldString(48, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(48)SecurityID=(").append(value).append(")")
}

object SecurityIDField {
  val TagId = 48  
  def decode(a: Option[Any]) : Option[SecurityIDField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[SecurityIDField]
  }

  def decode(a: Any) : Option[SecurityIDField] = a match {
    case v: String => Some(SecurityIDField(v))
    case v: SecurityIDField => Some(v)
    case _ => scala.Option.empty[SecurityIDField]
  } 
}
