package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20170521
  */
case class SecurityAltIDSourceField(override val value: String) extends SfFieldString(456, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(456)SecurityAltIDSource=(").append(value).append(")")
}

object SecurityAltIDSourceField {
  val TagId = 456  
  def decode(a: Option[Any]) : Option[SecurityAltIDSourceField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[SecurityAltIDSourceField]
  }

  def decode(a: Any) : Option[SecurityAltIDSourceField] = a match {
    case v: String => Some(SecurityAltIDSourceField(v))
    case v: SecurityAltIDSourceField => Some(v)
    case _ => scala.Option.empty[SecurityAltIDSourceField]
  } 
}
