package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20170404
  */
case class SecurityListDescField(override val value: String) extends SfFieldString(1467, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(1467)SecurityListDesc=(").append(value).append(")")
}

object SecurityListDescField {
  val TagId = 1467  
  def decode(a: Option[Any]) : Option[SecurityListDescField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[SecurityListDescField]
  }

  def decode(a: Any) : Option[SecurityListDescField] = a match {
    case v: String => Some(SecurityListDescField(v))
    case v: SecurityListDescField => Some(v)
    case _ => scala.Option.empty[SecurityListDescField]
  } 
}
