package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldInt

/**
  * Generated by SackFix code generator on 20210314
  */
case class SecurityReportIDField(override val value: Int) extends SfFieldInt(964, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(964)SecurityReportID=(").append(value).append(")")
}

object SecurityReportIDField {
  val TagId = 964  
  def apply(value: String) = try {
    new SecurityReportIDField(value.toInt)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new SecurityReportID("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[SecurityReportIDField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[SecurityReportIDField]
  }

  def decode(a: Any) : Option[SecurityReportIDField] = a match {
    case v: String => Some(SecurityReportIDField(v))
    case v: Int => Some(SecurityReportIDField(v))
    case v: SecurityReportIDField => Some(v)
    case _ => scala.Option.empty[SecurityReportIDField]
  } 
}
