package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20210314
  */
case class SecuritySettlAgentCodeField(override val value: String) extends SfFieldString(177, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(177)SecuritySettlAgentCode=(").append(value).append(")")
}

object SecuritySettlAgentCodeField {
  val TagId = 177  
  def decode(a: Option[Any]) : Option[SecuritySettlAgentCodeField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[SecuritySettlAgentCodeField]
  }

  def decode(a: Any) : Option[SecuritySettlAgentCodeField] = a match {
    case v: String => Some(SecuritySettlAgentCodeField(v))
    case v: SecuritySettlAgentCodeField => Some(v)
    case _ => scala.Option.empty[SecuritySettlAgentCodeField]
  } 
}
