package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20170404
  */
case class SecuritySettlAgentContactPhoneField(override val value: String) extends SfFieldString(181, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(181)SecuritySettlAgentContactPhone=(").append(value).append(")")
}

object SecuritySettlAgentContactPhoneField {
  val TagId = 181  
  def decode(a: Option[Any]) : Option[SecuritySettlAgentContactPhoneField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[SecuritySettlAgentContactPhoneField]
  }

  def decode(a: Any) : Option[SecuritySettlAgentContactPhoneField] = a match {
    case v: String => Some(SecuritySettlAgentContactPhoneField(v))
    case v: SecuritySettlAgentContactPhoneField => Some(v)
    case _ => scala.Option.empty[SecuritySettlAgentContactPhoneField]
  } 
}
