package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldFloat

/**
  * Generated by SackFix code generator on 20170404
  */
case class SellVolumeField(override val value: Float) extends SfFieldFloat(331, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(331)SellVolume=(").append(value).append(")")
}

object SellVolumeField {
  val TagId = 331  
  def apply(value: String) = try {
    new SellVolumeField(value.toFloat)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new SellVolume("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[SellVolumeField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[SellVolumeField]
  }

  def decode(a: Any) : Option[SellVolumeField] = a match {
    case v: String => Some(SellVolumeField(v))
    case v: Float => Some(SellVolumeField(v))
    case v: Double => Some(SellVolumeField(v.toFloat))
    case v: Int => Some(SellVolumeField(v.toFloat))
    case v: SellVolumeField => Some(v)
    case _ => scala.Option.empty[SellVolumeField]
  } 
}
