package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20210314
  */
case class SettlPartyIDSourceField(override val value: String) extends SfFieldString(783, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(783)SettlPartyIDSource=(").append(value).append(")")
}

object SettlPartyIDSourceField {
  val TagId = 783  
  def decode(a: Option[Any]) : Option[SettlPartyIDSourceField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[SettlPartyIDSourceField]
  }

  def decode(a: Any) : Option[SettlPartyIDSourceField] = a match {
    case v: String => Some(SettlPartyIDSourceField(v))
    case v: Char => Some(SettlPartyIDSourceField(v.toString))
    case v: SettlPartyIDSourceField => Some(v)
    case _ => scala.Option.empty[SettlPartyIDSourceField]
  } 
}
