package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20170521
  */
case class SettlInstCodeField(override val value: String) extends SfFieldString(175, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(175)SettlInstCode=(").append(value).append(")")
}

object SettlInstCodeField {
  val TagId = 175  
  def decode(a: Option[Any]) : Option[SettlInstCodeField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[SettlInstCodeField]
  }

  def decode(a: Any) : Option[SettlInstCodeField] = a match {
    case v: String => Some(SettlInstCodeField(v))
    case v: SettlInstCodeField => Some(v)
    case _ => scala.Option.empty[SettlInstCodeField]
  } 
}
