package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldInt

/**
  * Generated by SackFix code generator on 20170521
  */
case class SettlPartySubIDTypeField(override val value: Int) extends SfFieldInt(786, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(786)SettlPartySubIDType=(").append(value).append(")")
}

object SettlPartySubIDTypeField {
  val TagId = 786  
  def apply(value: String) = try {
    new SettlPartySubIDTypeField(value.toInt)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new SettlPartySubIDType("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[SettlPartySubIDTypeField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[SettlPartySubIDTypeField]
  }

  def decode(a: Any) : Option[SettlPartySubIDTypeField] = a match {
    case v: String => Some(SettlPartySubIDTypeField(v))
    case v: Int => Some(SettlPartySubIDTypeField(v))
    case v: SettlPartySubIDTypeField => Some(v)
    case _ => scala.Option.empty[SettlPartySubIDTypeField]
  } 
}
