package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20170521
  */
case class SettleOnOpenFlagField(override val value: String) extends SfFieldString(966, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(966)SettleOnOpenFlag=(").append(value).append(")")
}

object SettleOnOpenFlagField {
  val TagId = 966  
  def decode(a: Option[Any]) : Option[SettleOnOpenFlagField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[SettleOnOpenFlagField]
  }

  def decode(a: Any) : Option[SettleOnOpenFlagField] = a match {
    case v: String => Some(SettleOnOpenFlagField(v))
    case v: SettleOnOpenFlagField => Some(v)
    case _ => scala.Option.empty[SettleOnOpenFlagField]
  } 
}
