package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldInt

/**
  * Generated by SackFix code generator on 20170404
  */
case class SharesIntField(override val value: Int) extends SfFieldInt(53, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(53)SharesInt=(").append(value).append(")")
}

object SharesIntField {
  val TagId = 53  
  def apply(value: String) = try {
    new SharesIntField(value.toInt)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new SharesInt("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[SharesIntField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[SharesIntField]
  }

  def decode(a: Any) : Option[SharesIntField] = a match {
    case v: String => Some(SharesIntField(v))
    case v: Int => Some(SharesIntField(v))
    case v: SharesIntField => Some(v)
    case _ => scala.Option.empty[SharesIntField]
  } 
}
