package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20170521
  */
case class SideExecIDField(override val value: String) extends SfFieldString(1427, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(1427)SideExecID=(").append(value).append(")")
}

object SideExecIDField {
  val TagId = 1427  
  def decode(a: Option[Any]) : Option[SideExecIDField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[SideExecIDField]
  }

  def decode(a: Any) : Option[SideExecIDField] = a match {
    case v: String => Some(SideExecIDField(v))
    case v: SideExecIDField => Some(v)
    case _ => scala.Option.empty[SideExecIDField]
  } 
}
