package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldInt

/**
  * Generated by SackFix code generator on 20210314
  */
case class SideTrdRegTimestampTypeField(override val value: Int) extends SfFieldInt(1013, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(1013)SideTrdRegTimestampType=(").append(value).append(")")
}

object SideTrdRegTimestampTypeField {
  val TagId = 1013  
  def apply(value: String) = try {
    new SideTrdRegTimestampTypeField(value.toInt)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new SideTrdRegTimestampType("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[SideTrdRegTimestampTypeField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[SideTrdRegTimestampTypeField]
  }

  def decode(a: Any) : Option[SideTrdRegTimestampTypeField] = a match {
    case v: String => Some(SideTrdRegTimestampTypeField(v))
    case v: Int => Some(SideTrdRegTimestampTypeField(v))
    case v: SideTrdRegTimestampTypeField => Some(v)
    case _ => scala.Option.empty[SideTrdRegTimestampTypeField]
  } 
}
