package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldInt

/**
  * Generated by SackFix code generator on 20170404
  */
case class SideValueIndField(override val value: Int) extends SfFieldInt(401, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(401)SideValueInd=(").append(value).append(")").append(SideValueIndField.fixDescriptionByValue.getOrElse(value,""))
}

object SideValueIndField {
  val TagId = 401 
  val Sidevalue1=1
  val Sidevalue2=2
  lazy val fixDescriptionByValue = Map(1->"SIDEVALUE1",2->"SIDEVALUE2")
 
  def apply(value: String) = try {
    new SideValueIndField(value.toInt)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new SideValueInd("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[SideValueIndField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[SideValueIndField]
  }

  def decode(a: Any) : Option[SideValueIndField] = a match {
    case v: String => Some(SideValueIndField(v))
    case v: Int => Some(SideValueIndField(v))
    case v: SideValueIndField => Some(v)
    case _ => scala.Option.empty[SideValueIndField]
  } 
}
