package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20210314
  */
case class SideComplianceIDField(override val value: String) extends SfFieldString(659, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(659)SideComplianceID=(").append(value).append(")")
}

object SideComplianceIDField {
  val TagId = 659  
  def decode(a: Option[Any]) : Option[SideComplianceIDField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[SideComplianceIDField]
  }

  def decode(a: Any) : Option[SideComplianceIDField] = a match {
    case v: String => Some(SideComplianceIDField(v))
    case v: SideComplianceIDField => Some(v)
    case _ => scala.Option.empty[SideComplianceIDField]
  } 
}
