package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldInt

/**
  * Generated by SackFix code generator on 20210314
  */
case class SignatureLengthField(override val value: Int) extends SfFieldInt(93, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(93)SignatureLength=(").append(value).append(")")
}

object SignatureLengthField {
  val TagId = 93  
  def apply(value: String) = try {
    new SignatureLengthField(value.toInt)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new SignatureLength("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[SignatureLengthField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[SignatureLengthField]
  }

  def decode(a: Any) : Option[SignatureLengthField] = a match {
    case v: String => Some(SignatureLengthField(v))
    case v: Int => Some(SignatureLengthField(v))
    case v: SignatureLengthField => Some(v)
    case _ => scala.Option.empty[SignatureLengthField]
  } 
}
