package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20170404
  */
case class StandInstDbNameField(override val value: String) extends SfFieldString(170, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(170)StandInstDbName=(").append(value).append(")")
}

object StandInstDbNameField {
  val TagId = 170  
  def decode(a: Option[Any]) : Option[StandInstDbNameField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[StandInstDbNameField]
  }

  def decode(a: Any) : Option[StandInstDbNameField] = a match {
    case v: String => Some(StandInstDbNameField(v))
    case v: StandInstDbNameField => Some(v)
    case _ => scala.Option.empty[StandInstDbNameField]
  } 
}
