package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldFloat

/**
  * Generated by SackFix code generator on 20210314
  */
case class StartStrikePxRangeField(override val value: Float) extends SfFieldFloat(1202, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(1202)StartStrikePxRange=(").append(value).append(")")
}

object StartStrikePxRangeField {
  val TagId = 1202  
  def apply(value: String) = try {
    new StartStrikePxRangeField(value.toFloat)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new StartStrikePxRange("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[StartStrikePxRangeField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[StartStrikePxRangeField]
  }

  def decode(a: Any) : Option[StartStrikePxRangeField] = a match {
    case v: String => Some(StartStrikePxRangeField(v))
    case v: Float => Some(StartStrikePxRangeField(v))
    case v: Double => Some(StartStrikePxRangeField(v.toFloat))
    case v: Int => Some(StartStrikePxRangeField(v.toFloat))
    case v: StartStrikePxRangeField => Some(v)
    case _ => scala.Option.empty[StartStrikePxRangeField]
  } 
}
