package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20170521
  */
case class StateOrProvinceOfIssueField(override val value: String) extends SfFieldString(471, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(471)StateOrProvinceOfIssue=(").append(value).append(")")
}

object StateOrProvinceOfIssueField {
  val TagId = 471  
  def decode(a: Option[Any]) : Option[StateOrProvinceOfIssueField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[StateOrProvinceOfIssueField]
  }

  def decode(a: Any) : Option[StateOrProvinceOfIssueField] = a match {
    case v: String => Some(StateOrProvinceOfIssueField(v))
    case v: StateOrProvinceOfIssueField => Some(v)
    case _ => scala.Option.empty[StateOrProvinceOfIssueField]
  } 
}
