package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20170521
  */
case class StrategyParameterValueField(override val value: String) extends SfFieldString(960, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(960)StrategyParameterValue=(").append(value).append(")")
}

object StrategyParameterValueField {
  val TagId = 960  
  def decode(a: Option[Any]) : Option[StrategyParameterValueField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[StrategyParameterValueField]
  }

  def decode(a: Any) : Option[StrategyParameterValueField] = a match {
    case v: String => Some(StrategyParameterValueField(v))
    case v: StrategyParameterValueField => Some(v)
    case _ => scala.Option.empty[StrategyParameterValueField]
  } 
}
