package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20170404
  */
case class StrikeRuleIDField(override val value: String) extends SfFieldString(1223, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(1223)StrikeRuleID=(").append(value).append(")")
}

object StrikeRuleIDField {
  val TagId = 1223  
  def decode(a: Option[Any]) : Option[StrikeRuleIDField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[StrikeRuleIDField]
  }

  def decode(a: Any) : Option[StrikeRuleIDField] = a match {
    case v: String => Some(StrikeRuleIDField(v))
    case v: StrikeRuleIDField => Some(v)
    case _ => scala.Option.empty[StrikeRuleIDField]
  } 
}
