package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldFloat

/**
  * Generated by SackFix code generator on 20170521
  */
case class StrikePriceField(override val value: Float) extends SfFieldFloat(202, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(202)StrikePrice=(").append(value).append(")")
}

object StrikePriceField {
  val TagId = 202  
  def apply(value: String) = try {
    new StrikePriceField(value.toFloat)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new StrikePrice("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[StrikePriceField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[StrikePriceField]
  }

  def decode(a: Any) : Option[StrikePriceField] = a match {
    case v: String => Some(StrikePriceField(v))
    case v: Float => Some(StrikePriceField(v))
    case v: Double => Some(StrikePriceField(v.toFloat))
    case v: Int => Some(StrikePriceField(v.toFloat))
    case v: StrikePriceField => Some(v)
    case _ => scala.Option.empty[StrikePriceField]
  } 
}
