package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldFloat

/**
  * Generated by SackFix code generator on 20170521
  */
case class StrikeValueField(override val value: Float) extends SfFieldFloat(968, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(968)StrikeValue=(").append(value).append(")")
}

object StrikeValueField {
  val TagId = 968  
  def apply(value: String) = try {
    new StrikeValueField(value.toFloat)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new StrikeValue("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[StrikeValueField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[StrikeValueField]
  }

  def decode(a: Any) : Option[StrikeValueField] = a match {
    case v: String => Some(StrikeValueField(v))
    case v: Float => Some(StrikeValueField(v))
    case v: Double => Some(StrikeValueField(v.toFloat))
    case v: Int => Some(StrikeValueField(v.toFloat))
    case v: StrikeValueField => Some(v)
    case _ => scala.Option.empty[StrikeValueField]
  } 
}
