package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20170521
  */
case class TargetSubIDField(override val value: String) extends SfFieldString(57, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(57)TargetSubID=(").append(value).append(")")
}

object TargetSubIDField {
  val TagId = 57  
  def decode(a: Option[Any]) : Option[TargetSubIDField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[TargetSubIDField]
  }

  def decode(a: Any) : Option[TargetSubIDField] = a match {
    case v: String => Some(TargetSubIDField(v))
    case v: TargetSubIDField => Some(v)
    case _ => scala.Option.empty[TargetSubIDField]
  } 
}
