package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20210314
  */
case class TargetPartyIDField(override val value: String) extends SfFieldString(1462, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(1462)TargetPartyID=(").append(value).append(")")
}

object TargetPartyIDField {
  val TagId = 1462  
  def decode(a: Option[Any]) : Option[TargetPartyIDField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[TargetPartyIDField]
  }

  def decode(a: Any) : Option[TargetPartyIDField] = a match {
    case v: String => Some(TargetPartyIDField(v))
    case v: TargetPartyIDField => Some(v)
    case _ => scala.Option.empty[TargetPartyIDField]
  } 
}
