package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldFloat

/**
  * Generated by SackFix code generator on 20170521
  */
case class ThresholdAmountField(override val value: Float) extends SfFieldFloat(834, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(834)ThresholdAmount=(").append(value).append(")")
}

object ThresholdAmountField {
  val TagId = 834  
  def apply(value: String) = try {
    new ThresholdAmountField(value.toFloat)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new ThresholdAmount("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[ThresholdAmountField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[ThresholdAmountField]
  }

  def decode(a: Any) : Option[ThresholdAmountField] = a match {
    case v: String => Some(ThresholdAmountField(v))
    case v: Float => Some(ThresholdAmountField(v))
    case v: Double => Some(ThresholdAmountField(v.toFloat))
    case v: Int => Some(ThresholdAmountField(v.toFloat))
    case v: ThresholdAmountField => Some(v)
    case _ => scala.Option.empty[ThresholdAmountField]
  } 
}
