package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldFloat

/**
  * Generated by SackFix code generator on 20210314
  */
case class TickIncrementField(override val value: Float) extends SfFieldFloat(1208, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(1208)TickIncrement=(").append(value).append(")")
}

object TickIncrementField {
  val TagId = 1208  
  def apply(value: String) = try {
    new TickIncrementField(value.toFloat)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new TickIncrement("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[TickIncrementField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[TickIncrementField]
  }

  def decode(a: Any) : Option[TickIncrementField] = a match {
    case v: String => Some(TickIncrementField(v))
    case v: Float => Some(TickIncrementField(v))
    case v: Double => Some(TickIncrementField(v.toFloat))
    case v: Int => Some(TickIncrementField(v.toFloat))
    case v: TickIncrementField => Some(v)
    case _ => scala.Option.empty[TickIncrementField]
  } 
}
