package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20170404
  */
case class TimeBracketField(override val value: String) extends SfFieldString(943, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(943)TimeBracket=(").append(value).append(")")
}

object TimeBracketField {
  val TagId = 943  
  def decode(a: Option[Any]) : Option[TimeBracketField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[TimeBracketField]
  }

  def decode(a: Any) : Option[TimeBracketField] = a match {
    case v: String => Some(TimeBracketField(v))
    case v: TimeBracketField => Some(v)
    case _ => scala.Option.empty[TimeBracketField]
  } 
}
