package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldInt

/**
  * Generated by SackFix code generator on 20170521
  */
case class TotalAffectedOrdersField(override val value: Int) extends SfFieldInt(533, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(533)TotalAffectedOrders=(").append(value).append(")")
}

object TotalAffectedOrdersField {
  val TagId = 533  
  def apply(value: String) = try {
    new TotalAffectedOrdersField(value.toInt)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new TotalAffectedOrders("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[TotalAffectedOrdersField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[TotalAffectedOrdersField]
  }

  def decode(a: Any) : Option[TotalAffectedOrdersField] = a match {
    case v: String => Some(TotalAffectedOrdersField(v))
    case v: Int => Some(TotalAffectedOrdersField(v))
    case v: TotalAffectedOrdersField => Some(v)
    case _ => scala.Option.empty[TotalAffectedOrdersField]
  } 
}
