package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldInt

/**
  * Generated by SackFix code generator on 20210314
  */
case class TotNoStrikesField(override val value: Int) extends SfFieldInt(422, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(422)TotNoStrikes=(").append(value).append(")")
}

object TotNoStrikesField {
  val TagId = 422  
  def apply(value: String) = try {
    new TotNoStrikesField(value.toInt)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new TotNoStrikes("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[TotNoStrikesField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[TotNoStrikesField]
  }

  def decode(a: Any) : Option[TotNoStrikesField] = a match {
    case v: String => Some(TotNoStrikesField(v))
    case v: Int => Some(TotNoStrikesField(v))
    case v: TotNoStrikesField => Some(v)
    case _ => scala.Option.empty[TotNoStrikesField]
  } 
}
