package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldInt

/**
  * Generated by SackFix code generator on 20210314
  */
case class TotQuoteEntriesField(override val value: Int) extends SfFieldInt(304, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(304)TotQuoteEntries=(").append(value).append(")")
}

object TotQuoteEntriesField {
  val TagId = 304  
  def apply(value: String) = try {
    new TotQuoteEntriesField(value.toInt)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new TotQuoteEntries("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[TotQuoteEntriesField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[TotQuoteEntriesField]
  }

  def decode(a: Any) : Option[TotQuoteEntriesField] = a match {
    case v: String => Some(TotQuoteEntriesField(v))
    case v: Int => Some(TotQuoteEntriesField(v))
    case v: TotQuoteEntriesField => Some(v)
    case _ => scala.Option.empty[TotQuoteEntriesField]
  } 
}
