package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldUtcTimeStamp
import java.time.LocalDateTime
import org.sackfix.common.validated.fields.SfFixDateFormats

/**
  * Generated by SackFix code generator on 20170521
  */
case class TradSesOpenTimeField(override val value: LocalDateTime) extends SfFieldUtcTimeStamp(342, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(342)TradSesOpenTime=(").append(value).append(")")
}

object TradSesOpenTimeField {
  val TagId = 342  
  def apply(value: String) = try {
    new TradSesOpenTimeField(LocalDateTime.from(SfFixDateFormats.utcTimeStamp.parse(value)))
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new TradSesOpenTime("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[TradSesOpenTimeField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[TradSesOpenTimeField]
  }

  def decode(a: Any) : Option[TradSesOpenTimeField] = a match {
    case v: String => Some(TradSesOpenTimeField(v))
    case v: LocalDateTime => Some(TradSesOpenTimeField(v))
    case v: TradSesOpenTimeField => Some(v)
    case _ => scala.Option.empty[TradSesOpenTimeField]
  } 
}
