package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20170521
  */
case class TradeTypeField(override val value: String) extends SfFieldString(418, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(418)TradeType=(").append(value).append(")")
}

object TradeTypeField {
  val TagId = 418  
  def decode(a: Option[Any]) : Option[TradeTypeField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[TradeTypeField]
  }

  def decode(a: Any) : Option[TradeTypeField] = a match {
    case v: String => Some(TradeTypeField(v))
    case v: Char => Some(TradeTypeField(v.toString))
    case v: TradeTypeField => Some(v)
    case _ => scala.Option.empty[TradeTypeField]
  } 
}
