package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20210314
  */
case class TradSesReqIDField(override val value: String) extends SfFieldString(335, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(335)TradSesReqID=(").append(value).append(")")
}

object TradSesReqIDField {
  val TagId = 335  
  def decode(a: Option[Any]) : Option[TradSesReqIDField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[TradSesReqIDField]
  }

  def decode(a: Any) : Option[TradSesReqIDField] = a match {
    case v: String => Some(TradSesReqIDField(v))
    case v: TradSesReqIDField => Some(v)
    case _ => scala.Option.empty[TradSesReqIDField]
  } 
}
