package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldLocalMktDate
import java.time.LocalDate
import org.sackfix.common.validated.fields.SfFixDateFormats

/**
  * Generated by SackFix code generator on 20170404
  */
case class TradeOriginationDateField(override val value: LocalDate) extends SfFieldLocalMktDate(229, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(229)TradeOriginationDate=(").append(value).append(")")
}

object TradeOriginationDateField {
  val TagId = 229  
  def apply(value: String) = try {
    new TradeOriginationDateField(LocalDate.from(SfFixDateFormats.localMktDate.parse(value)))
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new TradeOriginationDate("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[TradeOriginationDateField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[TradeOriginationDateField]
  }

  def decode(a: Any) : Option[TradeOriginationDateField] = a match {
    case v: String => Some(TradeOriginationDateField(v))
    case v: LocalDate => Some(TradeOriginationDateField(v))
    case v: TradeOriginationDateField => Some(v)
    case _ => scala.Option.empty[TradeOriginationDateField]
  } 
}
