package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldUtcTimeStamp
import java.time.LocalDateTime
import org.sackfix.common.validated.fields.SfFixDateFormats

/**
  * Generated by SackFix code generator on 20210314
  */
case class TradSesStartTimeField(override val value: LocalDateTime) extends SfFieldUtcTimeStamp(341, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(341)TradSesStartTime=(").append(value).append(")")
}

object TradSesStartTimeField {
  val TagId = 341  
  def apply(value: String) = try {
    new TradSesStartTimeField(LocalDateTime.from(SfFixDateFormats.utcTimeStamp.parse(value)))
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new TradSesStartTime("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[TradSesStartTimeField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[TradSesStartTimeField]
  }

  def decode(a: Any) : Option[TradSesStartTimeField] = a match {
    case v: String => Some(TradSesStartTimeField(v))
    case v: LocalDateTime => Some(TradSesStartTimeField(v))
    case v: TradSesStartTimeField => Some(v)
    case _ => scala.Option.empty[TradSesStartTimeField]
  } 
}
