package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldUtcTimeStamp
import java.time.LocalDateTime
import org.sackfix.common.validated.fields.SfFixDateFormats

/**
  * Generated by SackFix code generator on 20170404
  */
case class TrdRegTimestampField(override val value: LocalDateTime) extends SfFieldUtcTimeStamp(769, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(769)TrdRegTimestamp=(").append(value).append(")")
}

object TrdRegTimestampField {
  val TagId = 769  
  def apply(value: String) = try {
    new TrdRegTimestampField(LocalDateTime.from(SfFixDateFormats.utcTimeStamp.parse(value)))
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new TrdRegTimestamp("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[TrdRegTimestampField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[TrdRegTimestampField]
  }

  def decode(a: Any) : Option[TrdRegTimestampField] = a match {
    case v: String => Some(TrdRegTimestampField(v))
    case v: LocalDateTime => Some(TrdRegTimestampField(v))
    case v: TrdRegTimestampField => Some(v)
    case _ => scala.Option.empty[TrdRegTimestampField]
  } 
}
