package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20210314
  */
case class UnderlyingSeniorityField(override val value: String) extends SfFieldString(1454, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(1454)UnderlyingSeniority=(").append(value).append(")")
}

object UnderlyingSeniorityField {
  val TagId = 1454  
  def decode(a: Option[Any]) : Option[UnderlyingSeniorityField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[UnderlyingSeniorityField]
  }

  def decode(a: Any) : Option[UnderlyingSeniorityField] = a match {
    case v: String => Some(UnderlyingSeniorityField(v))
    case v: UnderlyingSeniorityField => Some(v)
    case _ => scala.Option.empty[UnderlyingSeniorityField]
  } 
}
