package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldFloat

/**
  * Generated by SackFix code generator on 20170521
  */
case class UnderlyingCashAmountField(override val value: Float) extends SfFieldFloat(973, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(973)UnderlyingCashAmount=(").append(value).append(")")
}

object UnderlyingCashAmountField {
  val TagId = 973  
  def apply(value: String) = try {
    new UnderlyingCashAmountField(value.toFloat)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new UnderlyingCashAmount("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[UnderlyingCashAmountField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[UnderlyingCashAmountField]
  }

  def decode(a: Any) : Option[UnderlyingCashAmountField] = a match {
    case v: String => Some(UnderlyingCashAmountField(v))
    case v: Float => Some(UnderlyingCashAmountField(v))
    case v: Double => Some(UnderlyingCashAmountField(v.toFloat))
    case v: Int => Some(UnderlyingCashAmountField(v.toFloat))
    case v: UnderlyingCashAmountField => Some(v)
    case _ => scala.Option.empty[UnderlyingCashAmountField]
  } 
}
