package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldFloat

/**
  * Generated by SackFix code generator on 20210314
  */
case class UnderlyingPriceUnitOfMeasureQtyField(override val value: Float) extends SfFieldFloat(1425, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(1425)UnderlyingPriceUnitOfMeasureQty=(").append(value).append(")")
}

object UnderlyingPriceUnitOfMeasureQtyField {
  val TagId = 1425  
  def apply(value: String) = try {
    new UnderlyingPriceUnitOfMeasureQtyField(value.toFloat)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new UnderlyingPriceUnitOfMeasureQty("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[UnderlyingPriceUnitOfMeasureQtyField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[UnderlyingPriceUnitOfMeasureQtyField]
  }

  def decode(a: Any) : Option[UnderlyingPriceUnitOfMeasureQtyField] = a match {
    case v: String => Some(UnderlyingPriceUnitOfMeasureQtyField(v))
    case v: Float => Some(UnderlyingPriceUnitOfMeasureQtyField(v))
    case v: Double => Some(UnderlyingPriceUnitOfMeasureQtyField(v.toFloat))
    case v: Int => Some(UnderlyingPriceUnitOfMeasureQtyField(v.toFloat))
    case v: UnderlyingPriceUnitOfMeasureQtyField => Some(v)
    case _ => scala.Option.empty[UnderlyingPriceUnitOfMeasureQtyField]
  } 
}
