package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20210314
  */
case class UnderlyingStipValueField(override val value: String) extends SfFieldString(889, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(889)UnderlyingStipValue=(").append(value).append(")")
}

object UnderlyingStipValueField {
  val TagId = 889  
  def decode(a: Option[Any]) : Option[UnderlyingStipValueField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[UnderlyingStipValueField]
  }

  def decode(a: Any) : Option[UnderlyingStipValueField] = a match {
    case v: String => Some(UnderlyingStipValueField(v))
    case v: UnderlyingStipValueField => Some(v)
    case _ => scala.Option.empty[UnderlyingStipValueField]
  } 
}
