package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldInt

/**
  * Generated by SackFix code generator on 20210314
  */
case class UnderlyingInstrumentPartyRoleField(override val value: Int) extends SfFieldInt(1061, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(1061)UnderlyingInstrumentPartyRole=(").append(value).append(")")
}

object UnderlyingInstrumentPartyRoleField {
  val TagId = 1061  
  def apply(value: String) = try {
    new UnderlyingInstrumentPartyRoleField(value.toInt)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new UnderlyingInstrumentPartyRole("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[UnderlyingInstrumentPartyRoleField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[UnderlyingInstrumentPartyRoleField]
  }

  def decode(a: Any) : Option[UnderlyingInstrumentPartyRoleField] = a match {
    case v: String => Some(UnderlyingInstrumentPartyRoleField(v))
    case v: Int => Some(UnderlyingInstrumentPartyRoleField(v))
    case v: UnderlyingInstrumentPartyRoleField => Some(v)
    case _ => scala.Option.empty[UnderlyingInstrumentPartyRoleField]
  } 
}
