package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20170521
  */
case class UnderlyingSymbolSfxField(override val value: String) extends SfFieldString(312, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(312)UnderlyingSymbolSfx=(").append(value).append(")")
}

object UnderlyingSymbolSfxField {
  val TagId = 312  
  def decode(a: Option[Any]) : Option[UnderlyingSymbolSfxField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[UnderlyingSymbolSfxField]
  }

  def decode(a: Any) : Option[UnderlyingSymbolSfxField] = a match {
    case v: String => Some(UnderlyingSymbolSfxField(v))
    case v: UnderlyingSymbolSfxField => Some(v)
    case _ => scala.Option.empty[UnderlyingSymbolSfxField]
  } 
}
