package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20170521
  */
case class UnderlyingLegCFICodeField(override val value: String) extends SfFieldString(1344, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(1344)UnderlyingLegCFICode=(").append(value).append(")")
}

object UnderlyingLegCFICodeField {
  val TagId = 1344  
  def decode(a: Option[Any]) : Option[UnderlyingLegCFICodeField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[UnderlyingLegCFICodeField]
  }

  def decode(a: Any) : Option[UnderlyingLegCFICodeField] = a match {
    case v: String => Some(UnderlyingLegCFICodeField(v))
    case v: UnderlyingLegCFICodeField => Some(v)
    case _ => scala.Option.empty[UnderlyingLegCFICodeField]
  } 
}
