package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20210314
  */
case class UnderlyingStateOrProvinceOfIssueField(override val value: String) extends SfFieldString(593, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(593)UnderlyingStateOrProvinceOfIssue=(").append(value).append(")")
}

object UnderlyingStateOrProvinceOfIssueField {
  val TagId = 593  
  def decode(a: Option[Any]) : Option[UnderlyingStateOrProvinceOfIssueField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[UnderlyingStateOrProvinceOfIssueField]
  }

  def decode(a: Any) : Option[UnderlyingStateOrProvinceOfIssueField] = a match {
    case v: String => Some(UnderlyingStateOrProvinceOfIssueField(v))
    case v: UnderlyingStateOrProvinceOfIssueField => Some(v)
    case _ => scala.Option.empty[UnderlyingStateOrProvinceOfIssueField]
  } 
}
