package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20170404
  */
case class UnderlyingFXRateCalcField(override val value: String) extends SfFieldString(1046, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(1046)UnderlyingFXRateCalc=(").append(value).append(")").append(UnderlyingFXRateCalcField.fixDescriptionByValue.getOrElse(value,""))
}

object UnderlyingFXRateCalcField {
  val TagId = 1046 
  val Multiply="M"
  val Divide="D"
  lazy val fixDescriptionByValue = Map("M"->"MULTIPLY","D"->"DIVIDE")
 
  def decode(a: Option[Any]) : Option[UnderlyingFXRateCalcField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[UnderlyingFXRateCalcField]
  }

  def decode(a: Any) : Option[UnderlyingFXRateCalcField] = a match {
    case v: String => Some(UnderlyingFXRateCalcField(v))
    case v: Char => Some(UnderlyingFXRateCalcField(v.toString))
    case v: UnderlyingFXRateCalcField => Some(v)
    case _ => scala.Option.empty[UnderlyingFXRateCalcField]
  } 
}
