package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20170521
  */
case class UnderlyingLegSecurityAltIDField(override val value: String) extends SfFieldString(1335, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(1335)UnderlyingLegSecurityAltID=(").append(value).append(")")
}

object UnderlyingLegSecurityAltIDField {
  val TagId = 1335  
  def decode(a: Option[Any]) : Option[UnderlyingLegSecurityAltIDField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[UnderlyingLegSecurityAltIDField]
  }

  def decode(a: Any) : Option[UnderlyingLegSecurityAltIDField] = a match {
    case v: String => Some(UnderlyingLegSecurityAltIDField(v))
    case v: UnderlyingLegSecurityAltIDField => Some(v)
    case _ => scala.Option.empty[UnderlyingLegSecurityAltIDField]
  } 
}
