package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20170521
  */
case class UnderlyingSecurityIDSourceField(override val value: String) extends SfFieldString(305, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(305)UnderlyingSecurityIDSource=(").append(value).append(")")
}

object UnderlyingSecurityIDSourceField {
  val TagId = 305  
  def decode(a: Option[Any]) : Option[UnderlyingSecurityIDSourceField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[UnderlyingSecurityIDSourceField]
  }

  def decode(a: Any) : Option[UnderlyingSecurityIDSourceField] = a match {
    case v: String => Some(UnderlyingSecurityIDSourceField(v))
    case v: UnderlyingSecurityIDSourceField => Some(v)
    case _ => scala.Option.empty[UnderlyingSecurityIDSourceField]
  } 
}
