package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20170404
  */
case class UnderlyingSecurityAltIDSourceField(override val value: String) extends SfFieldString(459, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(459)UnderlyingSecurityAltIDSource=(").append(value).append(")")
}

object UnderlyingSecurityAltIDSourceField {
  val TagId = 459  
  def decode(a: Option[Any]) : Option[UnderlyingSecurityAltIDSourceField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[UnderlyingSecurityAltIDSourceField]
  }

  def decode(a: Any) : Option[UnderlyingSecurityAltIDSourceField] = a match {
    case v: String => Some(UnderlyingSecurityAltIDSourceField(v))
    case v: UnderlyingSecurityAltIDSourceField => Some(v)
    case _ => scala.Option.empty[UnderlyingSecurityAltIDSourceField]
  } 
}
