package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldInt

/**
  * Generated by SackFix code generator on 20210314
  */
case class UnderlyingExerciseStyleField(override val value: Int) extends SfFieldInt(1419, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(1419)UnderlyingExerciseStyle=(").append(value).append(")")
}

object UnderlyingExerciseStyleField {
  val TagId = 1419  
  def apply(value: String) = try {
    new UnderlyingExerciseStyleField(value.toInt)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new UnderlyingExerciseStyle("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[UnderlyingExerciseStyleField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[UnderlyingExerciseStyleField]
  }

  def decode(a: Any) : Option[UnderlyingExerciseStyleField] = a match {
    case v: String => Some(UnderlyingExerciseStyleField(v))
    case v: Int => Some(UnderlyingExerciseStyleField(v))
    case v: UnderlyingExerciseStyleField => Some(v)
    case _ => scala.Option.empty[UnderlyingExerciseStyleField]
  } 
}
