package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldBoolean

/**
  * Generated by SackFix code generator on 20210314
  */
case class UnsolicitedIndicatorField(override val value: Boolean) extends SfFieldBoolean(325, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(325)UnsolicitedIndicator=(").append({if (value) "Y" else "N"}).append(")")
}

object UnsolicitedIndicatorField {
  val TagId = 325  
  def apply(value: String) = try {
    new UnsolicitedIndicatorField(value match {
      case "Y" => true
      case "N" => false
      case _ => throw new IllegalArgumentException("UnsolicitedIndicator.apply("+value+"] failed, bad value, expected Y or N.")
    })
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new UnsolicitedIndicator("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[UnsolicitedIndicatorField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[UnsolicitedIndicatorField]
  }

  def decode(a: Any) : Option[UnsolicitedIndicatorField] = a match {
    case v: String => Some(UnsolicitedIndicatorField(v))
    case v: Boolean => Some(UnsolicitedIndicatorField(v))
    case v: UnsolicitedIndicatorField => Some(v)
    case _ => scala.Option.empty[UnsolicitedIndicatorField]
  } 
}
