package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20210314
  */
case class UserRequestIDField(override val value: String) extends SfFieldString(923, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(923)UserRequestID=(").append(value).append(")")
}

object UserRequestIDField {
  val TagId = 923  
  def decode(a: Option[Any]) : Option[UserRequestIDField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[UserRequestIDField]
  }

  def decode(a: Any) : Option[UserRequestIDField] = a match {
    case v: String => Some(UserRequestIDField(v))
    case v: UserRequestIDField => Some(v)
    case _ => scala.Option.empty[UserRequestIDField]
  } 
}
