package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldFloat

/**
  * Generated by SackFix code generator on 20170404
  */
case class VolatilityField(override val value: Float) extends SfFieldFloat(1188, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(1188)Volatility=(").append(value).append(")")
}

object VolatilityField {
  val TagId = 1188  
  def apply(value: String) = try {
    new VolatilityField(value.toFloat)
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new Volatility("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[VolatilityField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[VolatilityField]
  }

  def decode(a: Any) : Option[VolatilityField] = a match {
    case v: String => Some(VolatilityField(v))
    case v: Float => Some(VolatilityField(v))
    case v: Double => Some(VolatilityField(v.toFloat))
    case v: Int => Some(VolatilityField(v.toFloat))
    case v: VolatilityField => Some(v)
    case _ => scala.Option.empty[VolatilityField]
  } 
}
